- composer.json
- composer.lock
- phpunit.xml
Convenience to be able to include PHPUnit and run the suite from the root folder.
> Include PHPUnit in composer

- lib/Sabberworm/CSS/CSSList/CSSList.php
- lib/Sabberworm/CSS/RuleSet/RuleSet.php
- tests/Sabberworm/CSS/CSSList/DocumentTest.php
- tests/Sabberworm/CSS/RuleSet/DeclarationBlockTest.php
> Support for overriding all contents and rules

- lib/Sabberworm/CSS/Parser.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/unopened-close-brackets.css
> Discard unopened close brackets

- lib/Sabberworm/CSS/Parser.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/trailing-whitespace.css
> Fix UnexpectedTokenException caused by trailing whitespace

- tests/files/missing-property-value.css
> Add missing missing-property-value.css file

- lib/Sabberworm/CSS/Parser.php
> Fix error with charset.

- tests/Sabberworm/CSS/OutputFormatTest.php
- tests/Sabberworm/CSS/ParserTest.php
This gets the code base one more step towards PSR-12 compliance.
> Add missing method visibilties

- lib/Sabberworm/CSS/CSSList/CSSBlockList.php
- lib/Sabberworm/CSS/CSSList/CSSList.php
- lib/Sabberworm/CSS/OutputFormat.php
- lib/Sabberworm/CSS/Parsing/ParserState.php
- lib/Sabberworm/CSS/Property/AtRule.php
- lib/Sabberworm/CSS/Property/KeyframeSelector.php
- lib/Sabberworm/CSS/Property/Selector.php
- lib/Sabberworm/CSS/RuleSet/DeclarationBlock.php
- lib/Sabberworm/CSS/Settings.php
- tests/Sabberworm/CSS/OutputFormatTest.php
- tests/Sabberworm/CSS/ParserTest.php
- drop unused imports
- sort the imports
> Clean up imports

- src/Value/Size.php
This also fixes a PSR-12 violation concerning indentation.
> Simplify the size handling

- tests/OutputFormatTest.php
This brings the codebase one more step forward towards PSR-12
compliance.
> Split long lines in `OutputFormatTest.php`

- tests/RuleSet/LenientParsingTest.php
This brings the codebase one more step forward towards PSR-12
compliance.
> Split long lines in `LenientParsingTest.php`

- composer.json
- tests/CSSList/AtRuleBlockListTest.php
- tests/CSSList/DocumentTest.php
- tests/OutputFormatTest.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
- tests/RuleSet/LenientParsingTest.php
Also add PSR-4 dev-autoloading for this namespace.
> Move the tests to a separate PHP namespace

- phpcs.xml
> Enfore the short array syntax

- src/Parser.php
Also add a note concerning a bug that will be fixed in a separate change.
> Add type annotations for `Parser`

- src/CSSList/Document.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
Mark the code as to be removed in the next major version (which would
be in line with Semantic versioning).
> Mention when deprecated code will be removed

- src/Value/Value.php
> Fix a typo in a variable name

- composer.json
- prefer packages over Git
- sort the dependencies
Also actually sort the dependencies.
> [TASK] Add some Composer settings

- composer.json
> [BUGFIX] Use the Composer-installed PHPStan for creating the baseline

- .github/workflows/ci.yml
This should improve CI performance a bit.
> [TASK] Switch the static analysis CI jobs to PHP 8.3

- config/php-cs-fixer.php
- src/CSSList/CSSBlockList.php
- src/OutputFormat.php
- src/Parsing/UnexpectedEOFException.php
- src/RuleSet/DeclarationBlock.php
- src/Value/Size.php
- tests/Comment/CommentTest.php
- tests/RuleSet/DeclarationBlockTest.php
> [TASK] Switch to the PER2 coding standard

- .github/workflows/ci.yml
This is the backport of #426 to the maintenance branch.
> [TASK] Also PHP-lint with PHP 8.3 on CI

- .phive/phars.xml
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.50.0
> [TASK] Update PHP-CS-Fixer

- src/RuleSet/DeclarationBlock.php
- src/Value/Size.php
This applies the rule TernaryToNullCoalescingRector.
For details see: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#ternarytonullcoalescingrector
> [CLEANUP] rector: Changes unneeded null check to ?? operator

- src/RuleSet/DeclarationBlock.php
This applies the rule LongArrayToShortArrayRector. For details see: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#longarraytoshortarrayrector
This applies the rule ListToArrayDestructRector. For details see: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#listtoarraydestructrector
> [CLEANUP] rector: Long array to short array and Change list() to array destruct

- config/rector.php
This enables the rector rule set for PHP 7.1.
> [TASK] Add rector ruleset php71

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/Value/CalcFunction.php
> [BUGFIX] Fix undefined local variable in `CalcFunction::parse()`

- CHANGELOG.md
> [CLEANUP] Add missing PR number to changelog

- CHANGELOG.md
- src/CSSList/CSSList.php
- tests/CSSList/DocumentTest.php
> [FEATURE] Add support for inserting an item in a CSSList (#545)

- CHANGELOG.md
- src/CSSList/Document.php
- src/RuleSet/DeclarationBlock.php
This is the backport of #714 and all those changes:
- #578
- #580
- #579
- #577
- #576
- #575
- #574
- #573
- #572
- #571
- #570
- #569
- #566
- #567
- #558
> [TASK] Deprecate the expansion of shorthand properties

- src/CSSList/Document.php
- src/Parser.php
- src/Parsing/Anchor.php
- src/Parsing/ParserState.php
- src/Property/AtRule.php
- src/Property/KeyframeSelector.php
- src/Property/Selector.php
- src/RuleSet/DeclarationBlock.php
This will help us avoid breaking things in backports.
> [TASK] State since which version code is `@internal`/`@deprecated`

- CONTRIBUTING.md
Copied without changes from our sister project.
> [DOCS] Add a section on development deps to `CONTRIBUTING.md`

- src/Value/Color.php
> [TASK] Add another native return type declaration

- config/rector.php
This change is almost identical to the [corresponding change for Emogrifier](https://github.com/MyIntervals/emogrifier/pull/1372). The only differences are that we're using PHPUnit 8 here, not PHPUnit 9, and PHP 7.2, not 7.3.
> [TASK] Add more Rector rules

- config/rector.php
> [FOLLOWUP] Use the PHP 7.2 language level for Rector

- src/CSSList/Document.php
> [TASK] Add some more native return types

- CONTRIBUTING.md
Copied from our sister project without any changes.
Part of #489
> [TASK] Add a section on git commits to `CONTRIBUTING.md`

- CONTRIBUTING.md
Copied without changes from our sister project.
Part of #489
> [TASK] Add a section on creating PRs to `CONTRIBUTING.md`

- tests/Unit/SettingsTest.php
> [TASK] Move `SettingsTest` to the unit tests

- docs/release-checklist.md
Copied without changes (except for the link to the releases list) from our sister project.
Part of #489.
> [TASK] Add a release checklist

- tests/Unit/CSSList/KeyFrameTest.php
> [TASK] Move `KeyFrameTest` to unit tests

- src/Value/Color.php
> [CLEANUP] Add `Color::getRealName` method

- tests/Unit/Value/SizeTest.php
Also make an anonymous function in the test static.
Part of #758.
> [TASK] Move `SizeTest` to unit tests

- src/CSSList/CSSBlockList.php
- src/RuleSet/DeclarationBlock.php
> [CLEANUP] Avoid Hungarian notation for `oSelector`

- src/CSSList/CSSList.php
- src/Property/Import.php
> [CLEANUP] Avoid Hungarian notation for `sMediaQuery`

- src/CSSList/CSSList.php
- src/Value/URL.php
> [CLEANUP] Avoid Hungarian notation for `sIdentifier`

- src/CSSList/Document.php
> [CLEANUP] Avoid Hungarian notation for `element`

- src/CSSList/CSSBlockList.php
- src/Value/ValueList.php
> [CLEANUP] Avoid Hungarian notation for `component`

- CHANGELOG.md
- src/Parsing/OutputException.php
- src/Parsing/ParserState.php
- src/Parsing/SourceException.php
- src/Parsing/UnexpectedTokenException.php
Also improve the type annotations.
Also fix the callers to get the tests green with the native types.
Part of #811
> [TASK] Use native type declarations for the exception classes

- tests/CSSList/AtRuleBlockListTest.php
- tests/Unit/CSSList/AtRuleBlockListTest.php
> [TASK] Move some `AtRulBlockList` tests to unit tests

- CHANGELOG.md
- src/Comment/Comment.php
> [TASK] Use native type declarations for `Comment`

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `offset`

- CHANGELOG.md
- src/CSSList/CSSList.php
- src/Comment/Commentable.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Rule/Rule.php
- src/RuleSet/RuleSet.php
> [TASK] Use native type declarations in `Commentable`

- tests/Unit/CSSList/DocumentTest.php
> [TASK] Add one more unit test for `Document`

- tests/Unit/CSSList/AtRuleBlockListTest.php
- tests/Unit/CSSList/DocumentTest.php
- tests/Unit/CSSList/KeyFrameTest.php
> [CLEANUP] Add some comments for grouping tests

- src/Parsing/SourceException.php
- src/Parsing/UnexpectedTokenException.php
> [CLEANUP] Avoid Hungarian notation in the exception classes

- CHANGELOG.md
- src/CSSList/AtRuleBlockList.php
> [TASK] Use native type declarations in `AtRuleBlockList`

- CHANGELOG.md
- src/Rule/Rule.php
> [TASK] Make the deprecation of the IE hack complete

- tests/Functional/ParserTest.php
> [TASK] Add the first basic functional tests for `Parser`

- src/RuleSet/RuleSet.php
> [CLEANUP] Avoid Hungarian notation for `sibling`

- tests/FunctionalDeprecated/Property/SelectorTest.php
> [TASK] Add tests for `Selector::__toString()`

- tests/Unit/Property/SelectorTest.php
> [TASK] Add unit tests for `Selector.selector`

- src/CSSList/CSSBlockList.php
- src/CSSList/Document.php
- tests/Unit/CSSList/CSSBlockListTest.php
- tests/Unit/CSSList/DocumentTest.php
Move this method up without any changes to the method or its callers.
We'll clean this up in later changes.
Part of #994.
> [TASK] Move up `getAllRuleSets` to `CSSBlockList`

- tests/Unit/Value/ValueTest.php
Remove logic to make the data provider easier to grok.
> [CLEANUP] Simplify a data provider

- src/Value/Value.php
> [CLEANUP] Avoid Hungarian notation for `value`

- CHANGELOG.md
- src/OutputFormat.php
- src/OutputFormatter.php
This is the V8.x backport of #896.
> [TASK] Mark `OutputFormatter` as `@internal`

- src/Value/URL.php
> [CLEANUP] Avoid Hungarian notation for `character`

- src/Value/Size.php
> [CLEANUP] Avoid Hungarian notation in `Size`

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `peek`

- CHANGELOG.md
- src/CSSList/CSSList.php
- src/Value/Value.php
These are some random changes the Rector would do as a result of the changes of some open PRs.
> [TASK] Add some more type declarations

- CHANGELOG.md
- src/Parser.php
> [TASK] Use native type declarations in `Parser`

- CHANGELOG.md
- src/Parsing/Anchor.php
> [TASK] Use native type declarations in `Anchor`

- config/phpstan-baseline.neon
- src/CSSList/AtRuleBlockList.php
> [CLEANUP] Avoid magic method forwarding in `AtRuleBlockList`

- config/phpstan-baseline.neon
- src/Rule/Rule.php
> [CLEANUP] Avoid magic method forwarding in `Rule`

- config/phpstan-baseline.neon
- src/CSSList/CSSList.php
> [CLEANUP] Avoid magic method forwarding in `CSSList`

- config/phpstan-baseline.neon
- src/Property/Import.php
> [CLEANUP] Avoid magic method forwarding in `Import`

- config/phpstan-baseline.neon
- src/CSSList/KeyFrame.php
> [CLEANUP] Avoid magic method forwarding in `KeyFrame`

- config/phpstan-baseline.neon
- src/RuleSet/DeclarationBlock.php
> [CLEANUP] Avoid magic method forwarding in `DeclarationBlock`

- tests/Unit/Value/URLTest.php
> [TASK] Add some basic unit tests for `URL`

- CHANGELOG.md
- src/Value/URL.php
> [TASK] Add native type declarations in `URL`

- CHANGELOG.md
- src/CSSList/CSSList.php
- src/RuleSet/RuleSet.php
> [TASK] Add native return type for `render*` methods

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/Value/CSSString.php
> [TASK] Add native type declarations for `CSSString`

- src/Value/ValueList.php
Also polish some PHPDoc type annotations.
Part of #811.
> [TASK] Add native type declarations for `ValueList`

- tests/Unit/RuleSet/RuleSetTest.php
> [TASK] Add unit tests for `RuleSet::getRulesAssoc`

- src/RuleSet/RuleSet.php
> [TASK] Update `RuleSet::addRule` to use `getLineNumber`

- src/RuleSet/DeclarationBlock.php
This correction is not worthy of a changelog entry or any tests.
> [BUGFIX] Correct an exception message

- README.md
> [DOCS] Reorder some lines in the class diagram (part 5)

- README.md
> [DOCS] Reorder some lines in the class diagram (part 7)

- README.md
> [DOCS] Reorder some lines in the class diagram (part 8)

- README.md
> [DOCS] Reorder some lines in the class diagram (part 10)

- README.md
> [DOCS] Reorder some lines in the class diagram (part 12)

- .github/dependabot.yml
- CHANGELOG.md
- composer.json
> [TASK] Prepare release of version 9.0.0

- CHANGELOG.md
- src/Value/Size.php
Also use typesafe comparisons in the affected line.
Part of #1168
> [BUGFIX] Use safe preg functions in `Size`

- .github/dependabot.yml
- composer.json
This will prevent unsafe function usage from getting added.
Closes #1168
> [TASK] Add PHPStan rules for Safe-PHP
