- lib/Sabberworm/CSS/Parser.php
The basic idea is to use an array of characters instead of string processing.
**Benchmark**
For test I took the current css-file from github.com: https://assets-cdn.github.com/assets/github-a15e59d993eb0844d736a04652f63d465d909127e84cf7cd27073076df530f05.css
```php
$source = file_get_contents('https://assets-cdn.github.com/assets/github-a15e59d993eb0844d736a04652f63d465d909127e84cf7cd27073076df530f05.css');
$time = microtime(true);
$parser = new Sabberworm\CSS\Parser($source);
$css = $parser->parse();
var_dump(microtime(true) - $time);
```
On the my machine I received the following results:
before `float(180.93577218056)`
after `float(1.1720938682556)`
> Increase performance up to 15000%

- lib/Sabberworm/CSS/Parser.php
This is continue for #98:
* Support non-UTF-8 multibyte charset
* Split text when `setCharset` calling
@sabberworm Did you mean this?
> Charset issues

- lib/Sabberworm/CSS/CSSList/AtRuleBlockList.php
- lib/Sabberworm/CSS/CSSList/CSSBlockList.php
- lib/Sabberworm/CSS/CSSList/CSSList.php
- lib/Sabberworm/CSS/CSSList/Document.php
- lib/Sabberworm/CSS/CSSList/KeyFrame.php
- lib/Sabberworm/CSS/Parser.php
- lib/Sabberworm/CSS/Parsing/OutputException.php
- lib/Sabberworm/CSS/Parsing/SourceException.php
- lib/Sabberworm/CSS/Parsing/UnexpectedTokenException.php
- lib/Sabberworm/CSS/Property/CSSNamespace.php
- lib/Sabberworm/CSS/Property/Charset.php
- lib/Sabberworm/CSS/Property/Import.php
- lib/Sabberworm/CSS/Renderable.php
- lib/Sabberworm/CSS/Rule/Rule.php
- lib/Sabberworm/CSS/RuleSet/AtRuleSet.php
- lib/Sabberworm/CSS/RuleSet/DeclarationBlock.php
- lib/Sabberworm/CSS/RuleSet/RuleSet.php
- lib/Sabberworm/CSS/Value/CSSFunction.php
- lib/Sabberworm/CSS/Value/CSSString.php
- lib/Sabberworm/CSS/Value/Color.php
- lib/Sabberworm/CSS/Value/PrimitiveValue.php
- lib/Sabberworm/CSS/Value/RuleValueList.php
- lib/Sabberworm/CSS/Value/Size.php
- lib/Sabberworm/CSS/Value/URL.php
- lib/Sabberworm/CSS/Value/Value.php
- lib/Sabberworm/CSS/Value/ValueList.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/line-numbers.css
AMP HTML is a restricted subset of HTML (See https://www.ampproject.org/ for more details) and the AMP PHP Library provide validation and HTML to AMP HTML conversion utilities. We're using the `masterminds/html5-php` library to parse HTML5 and we're using `sabberworm/php-css-parser` to parse the CSS in the [AMP PHP Library](https://github.com/Lullabot/amp-library)
After parsing the CSS parse we report any problems in the CSS (for e.g. `!important` is disallowed in the AMP dialect of HTML, we use the `sabberworm` parser to find all the uses of `!important` for instance)
Now the CSS supplied by the user could be hundreds / thousands of lines long. So its not useful to simply say that `!important` was used and is not allowed. We should be able to say _which line_ the problem occurred.
This …
> Add line number support in the sabberworm CSS parser

- lib/Sabberworm/CSS/Parser.php
- lib/Sabberworm/CSS/Rule/Rule.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/ie-hacks.css
For your consideration. This allows for \0 and \9 to remain as they are intended. And will throw an exception when they are found in strict mode. Again, that to be able to parse Bootstrap 4.
> Support for IE hack parsing in lenient mode

- lib/Sabberworm/CSS/CSSList/CSSList.php
- lib/Sabberworm/CSS/Comment/Comment.php
- lib/Sabberworm/CSS/Comment/Commentable.php
- lib/Sabberworm/CSS/Parser.php
- lib/Sabberworm/CSS/Property/AtRule.php
- lib/Sabberworm/CSS/Property/CSSNamespace.php
- lib/Sabberworm/CSS/Property/Charset.php
- lib/Sabberworm/CSS/Property/Import.php
- lib/Sabberworm/CSS/Rule/Rule.php
- lib/Sabberworm/CSS/RuleSet/RuleSet.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/comments.css
The following patch is adding primary support to parsing comments, it does not try to do everything and it does not include the render part (as we don't need it) but hopefully it'll be useful to others.
In short, for the most generic cases, it adds the comments preceding a statement to the statement itself. See the test for more info.
X-ref: #38
> Primary support for comment parsing

- lib/Sabberworm/CSS/RuleSet/RuleSet.php
I'm currently using this lib to auto-prefix css rules for a wider browser support without the need to manually add all those rules. This requires me to add the new prefixed rules before the unprefixed one. I Made some additions to allow you to specify the exact location where the final Rule should be:
> RuleSet::addRule() insert position support.

- lib/Sabberworm/CSS/OutputFormat.php
- lib/Sabberworm/CSS/Parser.php
- lib/Sabberworm/CSS/Value/CSSFunction.php
- lib/Sabberworm/CSS/Value/CalcFunction.php
- lib/Sabberworm/CSS/Value/CalcRuleValueList.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/-calc-no-space-around-minus.css
- tests/files/calc.css
> Add support for CSS3 calc

- lib/Sabberworm/CSS/Parser.php
- lib/Sabberworm/CSS/Value/LineName.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/-empty-grid-linename.css
- tests/files/empty-grid-linename.css
- tests/files/grid-linename.css
> Add support for grid line names

- lib/Sabberworm/CSS/Parser.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/calc-nested.css
- tests/files/calc.css
These changes fix issues with rules like `calc(-120% - 4px)` and `calc(8px + -50%)`
> Bug fix in calc parsing when the first operand is a negative value

- lib/Sabberworm/CSS/Parser.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/hex-alpha.css
In CSS4 this is valid #0062cc0f. These changes add support for that notation.
> Add support for CSS4 alpha channels in hex notation

- lib/Sabberworm/CSS/Parser.php
Browsers seem to be okay with incomplete documents, they just parse up to the last valid rule. I guess we should do the same in lenient mode.
> Suppress "Unexpected end of document" in lenient mode

- lib/Sabberworm/CSS/CSSList/CSSList.php
This PR adds `prepend` and `replace` methods.
Possible use case for `prepend` is to allow adding `@import` rules, since they must come first. 
Possible use case for `replace` is changing the charset.
> Add prepend and replace methods

- lib/Sabberworm/CSS/CSSList/CSSList.php
This PR adds a `splice` method to allow insert/replace one or more items at an arbitrary point in the list. This compliments #149 which added `prepend` and `replace` methods to `CSSList`. 
An example use case for this PR is to extract CSS properties with `!important` qualifiers as separate rules with higher-specificity selectors. Example usage:
https://github.com/ampproject/amp-wp/blob/c92e129333a8518088a37d47594079b537121d70/includes/sanitizers/class-amp-style-sanitizer.php#L1757-L1762
Also adds PhpDoc to surrounding methods.
> Add splice method to CSSList

- lib/Sabberworm/CSS/Value/Value.php
- tests/Sabberworm/CSS/ParserTest.php
Given this CSS:
```css
div {
display: inline-block;
display:
}
```
I'm getting a PHP notice:
```
PHP Notice:  Undefined offset: 0 in .../sabberworm/php-css-parser/lib/Sabberworm/CSS/Value/Value.php on line 58
```
This PR fixes that problem by improving the resiliency to bad CSS.
> Fix undefined index notice when property lacks value

- .travis.yml
HHVM 4 on travis won’t run composer. Maybe there’s a workaround for that (install the dependencies using PHP and then use HHVM to run the tests?), but this needs further investigation.
> Use hhvm 3 explicitly

- composer.json
> Please note namespace declarations should end in `\\` to make sure the autoloader responds exactly.
https://getcomposer.org/doc/04-schema.md#psr-0
> Namespace declarations should end in `\\`

- lib/Sabberworm/CSS/Value/Size.php
Size units must be ordered longest first as the FIXME states. Example of an error is parsing `vmin` - it ends up as `vm in`
> Bug fix in parsing size units

- lib/Sabberworm/CSS/Parsing/ParserState.php
A PHP warning is being raised in PHP 7.3:
> `PHP Warning: count(): Parameter must be an array or an object that implements Countable in .../sabberworm/php-css-parser/lib/Sabberworm/CSS/Parsing/ParserState.php on line 30`
This was reported a couple times in the context of the AMP plugin for WordPress:
* https://wordpress.org/support/topic/php-7-3-9-warning-causing-timeout-on-amp-urls/
* https://github.com/ampproject/amp-wp/issues/1915#issuecomment-539758026
The suggested fix is to ensure that `count()` is only being done with `aText` when it has been populated with an array value.
> Fix PHP 7.3 warning when using count() on non-array value

- lib/Sabberworm/CSS/CSSList/CSSList.php
- lib/Sabberworm/CSS/Property/KeyframeSelector.php
- lib/Sabberworm/CSS/Property/Selector.php
- lib/Sabberworm/CSS/RuleSet/DeclarationBlock.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/keyframe-selector-validation.css
The regex for validating keyframe selectors should be slightly different to cover the "n%" part.
> Keyframe selector validation

- lib/Sabberworm/CSS/CSSList/CSSList.php
With the latest changes in parsing the media query for @import statements the media query ends up as the empty string instead of `null` and causes an unnecessary white space in the output.
> Fix @import's output when there is no media query

- lib/Sabberworm/CSS/Rule/Rule.php
The casing of custom property names must be preserved as described in this document https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
> Preserve casing for CSS var names

- lib/Sabberworm/CSS/Parsing/ParserState.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/identifier-escapes.css
When parsing identifiers take into account the character rules described here: https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier and escape any character outside of the list of allowed characters.
Amongst other things this resolves issues with unquoted font family definitions like:
```CSS
font: 14px Font Awesome\ 5 Pro;
```
> Escape identifier characters which are outside of the allowed range

- lib/Sabberworm/CSS/Value/Color.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/files/colortest.css
I tried to fix #196. Not sure if it is good solution, but at least it works ;)
> Fix var function inside color functions

- lib/Sabberworm/CSS/Value/Size.php
Currently e.g. `1vmax` is rendered as `1vm ax`. Removing `vm` from ABSOLUTE_SIZE_UNITS fixes that issue. Afaik there is no such unit as `vm`.
> Removed vm unit from ABSOLUTE_SIZE_UNITS

- lib/Sabberworm/CSS/Parsing/ParserState.php
- lib/Sabberworm/CSS/Rule/Rule.php
- lib/Sabberworm/CSS/RuleSet/DeclarationBlock.php
- lib/Sabberworm/CSS/RuleSet/RuleSet.php
- tests/Sabberworm/CSS/RuleSet/DeclarationBlockTest.php
Order of rules will now be preserved in most cases when expanding shorthands
> Fixes #203

- .github/workflows/ci.yml
This ensures that the PHP files have valid syntax, and blocks the unit
tests if there are any errors found.
> Add PHP linting to the CI build

- .github/workflows/ci.yml
The code coverage is only created for one PHP version (the highest version)
per build as there is no point to have multiple code coverage uploads
for the same code change.
> Create code coverage during the CI builds

- lib/Sabberworm/CSS/CSSList/AtRuleBlockList.php
- lib/Sabberworm/CSS/CSSList/CSSList.php
- lib/Sabberworm/CSS/CSSList/Document.php
- lib/Sabberworm/CSS/CSSList/KeyFrame.php
- lib/Sabberworm/CSS/Parser.php
- lib/Sabberworm/CSS/Property/AtRule.php
- lib/Sabberworm/CSS/Property/CSSNamespace.php
- lib/Sabberworm/CSS/Property/Charset.php
- lib/Sabberworm/CSS/Property/Import.php
- lib/Sabberworm/CSS/Renderable.php
- lib/Sabberworm/CSS/Rule/Rule.php
- lib/Sabberworm/CSS/RuleSet/AtRuleSet.php
- lib/Sabberworm/CSS/RuleSet/DeclarationBlock.php
- lib/Sabberworm/CSS/RuleSet/RuleSet.php
- lib/Sabberworm/CSS/Value/CSSFunction.php
- lib/Sabberworm/CSS/Value/CSSString.php
- lib/Sabberworm/CSS/Value/CalcRuleValueList.php
- lib/Sabberworm/CSS/Value/Color.php
- lib/Sabberworm/CSS/Value/LineName.php
- lib/Sabberworm/CSS/Value/Size.php
- lib/Sabberworm/CSS/Value/URL.php
- lib/Sabberworm/CSS/Value/ValueList.php
This will help static type analysis tools.
> Add some PHPDoc type annotations

- .github/workflows/ci.yml
This fixes build failures on pull requests from forks (where
usually no authentication token for the code coverage is set).
> Stop trying to upload the coverage if there is no auth token

- .github/workflows/ci.yml
- CHANGELOG.md
- composer.json
Now the PHP version requirement is on par with WordPress:
https://wordpress.org/support/article/requirements/
Fixes #207
> Require PHP >= 5.6

- .gitattributes
- .gitignore
- .phive/phars.xml
- composer.json
- phpcs.xml
There now are the following new Composer scripts:
- `ci`: run all CI-related Composer scripts
- `ci:static` run the static code analysis
- `ci:php:sniff` run PHP_CodeSniffer
- `fix:php` fix the autofixable PHP code warnings
- `fix:php:sniff` fix the autofixable PHP_CodeSniffer warnings
For starters, we have a sniff that checks for the PSR-12 standard.
(The CI builds do not run this check as the files are not
PSR-12 compliant yet at this point.)
> Add Composer scripts for code sniffing and autofixing

- lib/Sabberworm/CSS/CSSList/CSSList.php
- lib/Sabberworm/CSS/CSSList/Document.php
- lib/Sabberworm/CSS/OutputFormat.php
- lib/Sabberworm/CSS/Parsing/ParserState.php
- lib/Sabberworm/CSS/Property/AtRule.php
- lib/Sabberworm/CSS/Property/Import.php
- lib/Sabberworm/CSS/Rule/Rule.php
- lib/Sabberworm/CSS/RuleSet/DeclarationBlock.php
- lib/Sabberworm/CSS/RuleSet/RuleSet.php
- lib/Sabberworm/CSS/Settings.php
- lib/Sabberworm/CSS/Value/CSSString.php
- lib/Sabberworm/CSS/Value/CalcFunction.php
- lib/Sabberworm/CSS/Value/Color.php
- lib/Sabberworm/CSS/Value/Size.php
- lib/Sabberworm/CSS/Value/Value.php
- lib/Sabberworm/CSS/Value/ValueList.php
- tests/Sabberworm/CSS/OutputFormatTest.php
- tests/Sabberworm/CSS/ParserTest.php
- tests/Sabberworm/CSS/RuleSet/LenientParsingTest.php
This brings the code one step forward towards PSR-12 compliance.
> Keep more lines under 120 characters

- .github/workflows/ci.yml
We cannot (easily) run the unit tests with PHP 8 yet as long as we still
support PHP 5.6 because there is no version of PHPUnit that runs on
PHP from 5.6 up to 8.0.
> Add linting with PHP 8 to the CI builds

- lib/Sabberworm/CSS/CSSList/Document.php
- lib/Sabberworm/CSS/RuleSet/RuleSet.php
Intersection types like `string|int` must not be enclosed in
parenthesis in order to be recognized.
Also drop unnecessary curly braces for an `@see` annotation.
> Drop incorrect parenthesis around PHPDoc type annotations

- .gitattributes
- .github/workflows/ci.yml
- .gitignore
- .phive/phars.xml
- composer.json
- phpstan-baseline.neon
- phpstan.neon.dist
Add Composer scripts for checking the code with PHPStan (while using
a baseline) and for updating the baseline.
When we fix PHPStan-reported issues (or update the PHPStan configuration),
we can update the baseline bit by bit until all issues are fixed.
> Add static type analysis with PHPStan

- .gitattributes
A path isn't enough - we also need the `export-ignore`.
> Fix faulty `.gitattributes` entry for the PHIVE configuration file

- phpunit.xml
- tests/bootstrap.php
The bootstrap was used for autoloading. With the Composer autoloader,
it is no longer needed.
> Drop the PHPUnit bootstrap

- tests/phpunit.xml
There already is a `phpunit.xml` in the project root, and there is no
need to have another copy in `tests/`.
Fixes #229
> Drop an unused and redundant `phpunit.xml`

- phpstan-baseline.neon
- tests/Sabberworm/CSS/OutputFormatTest.php
- tests/Sabberworm/CSS/ParserTest.php
This fixes some PHPStan warnings.
> Fix the casing in the used PHPUnit namespaces

- .editorconfig
- .gitattributes
This helps contributors get the basic formatting options in their IDEs
automatically set right. (The setting for PHP files complies to the
PSR-12 standard.)
This change does not autoformat any files with these settings, though.
> Add an `.editorconfig` file

- phpstan-baseline.neon
- phpstan.neon.dist
Now that there are fixes for all level 0 warnings, we can tackle
the next level of warnings.
> Raise PHPStan checks to level 1

- tests/Sabberworm/CSS/OutputFormatTest.php
This resolves a PSR-12 violation.
> Change a global constant to a class constant in the tests

- .gitattributes
- bin/quickdump.php
- composer.json
- phpstan.neon.dist
This tool is not related to the tests and hence should not be stored
in the `tests`  directory.
Also properly include the Composer autoload and add a short comment
explaning the purpose of the file.
> Move the quickdump tool out of the `tests` directory

- src/CSSList/AtRuleBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/CSSList/KeyFrame.php
- src/Comment/Comment.php
- src/OutputFormat.php
- src/Parsing/OutputException.php
- src/Parsing/ParserState.php
- src/Parsing/SourceException.php
- src/Parsing/UnexpectedEOFException.php
- src/Parsing/UnexpectedTokenException.php
- src/Property/CSSNamespace.php
- src/Property/Import.php
- src/Property/Selector.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CalcFunction.php
- src/Value/Color.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/Value.php
- src/Value/ValueList.php
- tests/OutputFormatTest.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
- tests/RuleSet/LenientParsingTest.php
This allows contributors to autoformat their changed files without
risking to also affect the unchanged code.
This change also fixes a bunch of PSR-12 violations, and it hopefully
also makes the code a bit nicer to read.
> Autoformat all PHP files with PhpStorm

- tests/ParserTest.php
This fixes all PSR-12 violations in this file.
These tests will get a lot shorter when they are refactored
to test only one piece of behavior per test method, and when
the tests are reduced to use minimal data. (This will happen
later in separate changes, though.)
> Break long lines in `ParserTest`

- src/CSSList/CSSBlockList.php
- src/OutputFormat.php
- src/OutputFormatter.php
- src/Parsing/ParserState.php
- src/Rule/Rule.php
- src/Value/CSSFunction.php
- src/Value/Color.php
- src/Value/LineName.php
- src/Value/Value.php
- src/Value/ValueList.php
Also add PHPDoc type annotations for parameters that have a name
implying that they should be an array, but that actually can also
be other types.
> Add array parameter type declarations

- tests/RuleSet/DeclarationBlockTest.php
This is the last step required to pass the PSR-12 rule set
of PHP_CodeSniffer.
> Split long lines in `DeclarationBlockTest`

- composer.json
Composer will list all commands with their descriptions when run
without any arguments.
Also autoformat the `composer.json` with PhpStorm.
> Add descriptions for all Composer scripts

- tests/ParserTest.php
- tests/RuleSet/LenientParsingTest.php
In the affected cases, we are already using forward slashes, and hence
can use them all the time.
> Stop using `DIRECTORY_SEPARATOR` in the tests

- src/Renderable.php
- src/Value/Value.php
Abstract methods that duplicate what already is required by the
implementing interface do not add any value.
Also add a type annotation to the interface.
> Drop pointless abstract methods

- src/CSSList/AtRuleBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/CSSList/KeyFrame.php
- src/Comment/Comment.php
- src/OutputFormatter.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Renderable.php
- src/Rule/Rule.php
- src/RuleSet/AtRuleSet.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/CalcRuleValueList.php
- src/Value/Color.php
- src/Value/LineName.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/Value.php
- src/Value/ValueList.php
- tests/CSSList/AtRuleBlockListTest.php
- tests/CSSList/DocumentTest.php
- tests/OutputFormatTest.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
- tests/RuleSet/LenientParsingTest.php
This makes the code more concise.
> Simplify FQCN

- src/CSSList/AtRuleBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/Comment/Comment.php
- src/OutputFormat.php
- src/OutputFormatter.php
- src/Parser.php
- src/Parsing/ParserState.php
- src/Property/AtRule.php
- src/Property/Import.php
- src/Property/KeyframeSelector.php
- src/Property/Selector.php
- src/Rule/Rule.php
- src/RuleSet/AtRuleSet.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Settings.php
- tests/ParserTest.php
Make them more useful for static code analysis, for human readers
and for rendering.
> Streamline the existing PHPDoc comments

- tests/OutputFormatTest.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
- tests/RuleSet/LenientParsingTest.php
These make sure that only the lines of the classes the testcases are
about are marked as covered, hence reducing false coverage.
> Add `@covers` annotations to the tests

- .github/workflows/ci.yml
Now that the code is PSR-12-compliant, we should run the code sniffer
in the CI pipeline to keep pull request from introducing new
code style issues.
> Run the code sniffer in the CI pipeline

- src/Value/CalcFunction.php
This change omits type annotations that are already covered by native
type declarations.
> Add type annotations for `CalcFunction`

- src/RuleSet/DeclarationBlock.php
Also polish the existing commits a bit.
> Add type annotations for `DeclarationBlock`

- .github/workflows/ci.yml
- .gitignore
- .phive/phars.xml
- composer.json
- config/php-cs-fixer.php
This tool will help detect and fix more PSR-12 issues, and it will also
help modernize the tests so that it's easier to cover issues found by
PHPStan with tests.
> Add PHP CS Fixer to the toolchain

- composer.json
The iconv PHP extension is used in `ParserState` and hence needs to be
required.
The mbstring extension is optional, but helpful. So we should help
users discover this with a `suggest` entry in the `composer.json`.
> Add a requirement on iconv and suggest mbstring in `composer.json`

- src/CSSList/CSSList.php
- src/Comment/Commentable.php
- src/Property/CSSNamespace.php
- src/Property/Import.php
- src/Property/Selector.php
- src/RuleSet/RuleSet.php
Also copy these type annotations to the implementing classes.
> Add type annotations for `Commentable`

- src/CSSList/Document.php
- src/CSSList/KeyFrame.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Renderable.php
- src/RuleSet/AtRuleSet.php
- src/RuleSet/RuleSet.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/CalcRuleValueList.php
- src/Value/Color.php
- src/Value/LineName.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/ValueList.php
Also add type annotations to the implementing classes, and also drop
type annotations that duplicat the paramter type declarations.
> Add type annotations for `Renderable`

- config/php-cs-fixer.php
- tests/CSSList/AtRuleBlockListTest.php
- tests/CSSList/DocumentTest.php
- tests/OutputFormatTest.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
- tests/RuleSet/LenientParsingTest.php
- calls the assert methods statically
- use `@test` annotations instead of the `test` method name prefix
Also add PHP CS Fixer rules to automate these changes.
> Streamline the tests code style

- src/CSSList/CSSBlockList.php
- src/CSSList/Document.php
Also fix some associated type annotations that have turned out to
be incorrect.
> Add type annotations for `Document`

- CHANGELOG.md
There should be only one level of sorting, not two levels of sorting
with different directions (which made finding out what has changed
latest a real brain-twister).
> Sort the CHANGELOG entries chronologically

- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
Assertions should be very specific in order to catch incorrect types
or incorrectly-ordered arrays.
> Use `assertSame` whereever possible in the tests

- src/Property/KeyframeSelector.php
- src/Property/Selector.php
There is no need to use tabs here, and now the indentation is
consistent with the indentation used for the PHP code.
> Use spaces for indenting regular expressions

- src/Value/ValueList.php
PHPStan requires type annotations to be single-line.
> Do not split type annotations over multiple lines

- .github/workflows/ci.yml
- install all tools in one step instead of only one tool at a time
- install the exact registered version instead of updating
(which avoid version-dependent differences between CI and the
local environment)
- provide the fingerprints of the trusted GPG keys with which the
PHARs are signed so that the faked pseudo-interactive "yes"
confirmation is not needed anymore
> Install the development tools in the CI build the proper way

- .github/workflows/ci.yml
We currently cannot run the unit tests with PHP 8.1, but at least now
we can be sure our code does not have syntax that is incompatible
with PHP 8.1.
> Also run PHP-linting with PHP 8.1

- src/Value/Size.php
- tests/ParserTest.php
- tests/fixtures/values.css
This fixes merge conflicts for the key change in https://github.com/sabberworm/PHP-CSS-Parser/pull/193 which replaces the invalid `turns` init with `turn`, as identified by @pierlon:
> Also, there is no such unit named `turns`, but there is one called `turn` ([ref](https://drafts.csswg.org/css-values-3/#turn)), which I suppose is what was meant here 😄.
The use of `turns` in this codebase goes back [10 years](https://github.com/sabberworm/PHP-CSS-Parser/blame/7675640abec375a6c3c99590326bd78c3a7ec45d/lib/Sabberworm/CSS/Value/Size.php#L42).
> Replace invalid `turns` unit with `turn`

- src/Rule/Rule.php
Rules can have string values, and the type annotations should allow this
to avoid type analysis warnings in code using this library.
> Also allow string values for rules

- src/CSSList/AtRuleBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/CSSList/KeyFrame.php
- src/OutputFormat.php
- src/OutputFormatter.php
- src/Parsing/ParserState.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Rule/Rule.php
- src/RuleSet/AtRuleSet.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- tests/Comment/CommentTest.php
- tests/ParserTest.php
- tests/fixtures/comments.css
Hi,
was banging my head against the wall as my css comments would vanish when using a autoprefixer repo that utilizes this repo.
Found out that the issue was that comments are only partly implemented in this repo: they are recognized, but when rendering the parsed css code they are not added back.
So I rolled up my sleeves and did this PR.
This PR does two things:
1. fix the comments implementation as only the first comments where taken and not the subsequent comments in a CSSList
2. adds the comments back into the rendered CSS (as also requested in #38 )
So this is my first PR in this repo, would love to have some feedback / discussion / tests :)
Thanks in advance,
regards, Ruud
> retain CSSList and Rule comments when rendering CSS

- README.md
- src/CSSList/CSSList.php
Added `getSelectorsBySpecificity` to the README
> Documented getSelectorsBySpecificity

- .github/dependabot.yml
With this configuration, GitHub's Dependabot will create PR
to update the versions of the GitHub Actions we are using in
our CI pipeline.
> Add a Dependabot action for updating GitHub actions

- .github/workflows/ci.yml
This makes our usage of version numbers in the configuration file
consistent. It also ensures that no version number will get treated
as a number and rounded (e.g., 8.0 would have gotten rounded to 8).
> Quote all version numbers in the CI configuration

- README.md
Wrapped the dumped structure objects in a collapsible to make ReadMe easier to read.
> Add collapsible to improve readability

- README.md
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/Parser.php
- src/Parsing/ParserState.php
- src/Rule/Rule.php
- src/RuleSet/AtRuleSet.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Settings.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/Color.php
- src/Value/RuleValueList.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/Value.php
- src/Value/ValueList.php
This should help readers understand the code.
Also drop outdated documentation and polish the existing prose.
Fixes #300
> Sync the code documentation from the README to the source files

- CHANGELOG.md
- composer.json
I have compiled the changes that seemed relevant from the git history.
> [TASK] Prepare the 8.5.0 release

- tests/CSSList/DocumentTest.php
- tests/CSSList/KeyFrameTest.php
- tests/OutputFormatTest.php
This is a blocker for the upgrade to PHPUnit 8.
> [TASK] Add return types to `setUp()` in tests

- .gitignore
The corresponding file gets created by more recent versions of PHPUnit.
> [BUGFIX] Git-ignore the PHPUnit result cache

- tests/CSSList/AtRuleBlockListTest.php
- tests/CSSList/DocumentTest.php
- tests/CSSList/KeyFrameTest.php
- tests/Comment/CommentTest.php
- tests/OutputFormatTest.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
- tests/RuleSet/LenientParsingTest.php
- tests/Value/CalcRuleValueListTest.php
This helps communicate that the testcases are not intended to be subclassed.
Fixes #431
> [TASK] Make the testcases final

- phpunit.xml
- make things more strict
- stop caching the result (as we don't need this at the moment)
- make things more colorful
> [TASK] Configure PHPUnit some more

- .github/workflows/ci.yml
- .phive/phars.xml
- composer.json
This allows us to have PHPStan extensions, e.g., for PHPUnit.
> [TASK] Move PHPStan from PHIVE to Composer

- src/OutputFormatter.php
- src/Value/Value.php
- tests/Comment/CommentTest.php
Autoformat the code with the default PhpStorm settings (and re-run `composer fix:php` to minimize formatting-related changes when code is changed and autoformatted.
> [CLEANUP] Autoformat the code

- tests/CSSList/AtRuleBlockListTest.php
- tests/CSSList/DocumentTest.php
- tests/RuleSet/DeclarationBlockTest.php
Newer versions of PHPUnit require this, and we might as well do this now.
Closes #414
> [TASK] Make the data providers static

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
This makes the CI configuration easier to understand.
> [TASK] Move the coverage generation to a separate CI workflow

- composer.json
This enables PHPStan to understand certain PHPUnit-specific constructs.
> [FEATURE] Add a PHPUnit-specific extension to PHPStan

- CHANGELOG.md
- src/Parsing/ParserState.php
- src/Property/AtRule.php
- src/Property/KeyframeSelector.php
- src/Property/Selector.php
- src/Value/CalcFunction.php
- src/Value/Size.php
- tests/OutputFormatTest.php
This is a pre-patch to switching to the PER2 coding standard.
> [TASK] Add visibility to all class/interface constants

- CHANGELOG.md
- src/CSSList/CSSList.php
- tests/CSSList/AtRuleBlockListTest.php
The reverts the change to `CSSList` in
https://github.com/MyIntervals/PHP-CSS-Parser/commit/134f4e62fe8ab9f316425f3c0f480b3f4f52d804 and adds a comment that `null` is an expected return value when the end of the list (or block) is reached.
Fixes #352
> [BUGFIX] Allow at-rules to be parsed in strict mode (#456)

- src/Parsing/ParserState.php
- src/Property/AtRule.php
- src/Property/KeyframeSelector.php
- src/Property/Selector.php
> [TASK] Mark the public class constants as `@internal`

- .phive/phars.xml
- composer.json
On Windows, the `.phive` directory contains batch files that in turn invoke the phar installed elsewhere on the system.  To be compatible with both Linux and Windows, the file must be invoked directly via the shell, and without the file extension specified.
Fixes #479.
> [BUGFIX] Invoke PHIVE-installed tools via shell

- CHANGELOG.md
- src/Value/Color.php
- tests/ParserTest.php
- tests/fixtures/colortest.css
There is an issue when handling incorrect RGB colors which have lesser character numbers than 6. In this situation, we should probably either throw an exception OR define a fallback value for the color. 
In this PR, I have updated the code to use RGB(0,0,0) as the fallback color when this situation happens.
Thank you
> [BUGFIX] Handle incorrect RGB colors better

- README.md
The `ci` script now also runs `ci:dynamic` which in turn runs `ci:tests`.
The PHPUnit cache is only applicable if the configuration is to run previously failing tests first, which it isn't, hence `--do-not-cache-result`.
Also update the readme instructions for running all code checks.
Relates to #486.
> [FEATURE] Add Composer scripts to run unit tests

- CHANGELOG.md
- src/Value/Color.php
- tests/ParserTest.php
- tests/fixtures/colortest.css
Handle incorrect inputs color which have less than 6 chars
> [BUGFIX] Handle incorrect RGB colors better (#485)

- CHANGELOG.md
- src/Parsing/ParserState.php
- src/Property/AtRule.php
- src/Property/KeyframeSelector.php
- src/Property/Selector.php
- src/Value/CalcFunction.php
- src/Value/Size.php
This communicates that the constants must not be accessed from outside the project, thus preventing breakage as most of the constants will have a reduced visibility in version 9 (#470).
> [TASK] Mark all class constants as `@internal`

- CHANGELOG.md
- src/Value/Value.php
When there are many many elements in $aStack, starting the delimiter search from the beginning for each loop is very very slow. I addressed this by building a new array rather than modifying $aStack in place and iterating over it in a single pass. The particular 1.6M style string that was giving me trouble went from taking 4 minutes to parse to 5 seconds.
> [TASK] Avoid poor scaling of `array_search()` with very long arrays

- README.md
- composer.json
This is the change to `composer.json` which was inadvertently omitted in #488.
> [FEATURE] Add Composer scripts to run unit tests 

- README.md
Move the associations to the bottom of the code. Also sort them.
This helps us use an autogenerated diagram to which we add the associations (as the our tool of choice does not generate the associations for the diagram).
> [TASK] Reorder things in the class diagram source code

- README.md
This avoids spurious differences appearing after using an editor that automatically removes trailing whitespace.
> [DOCS] Remove trailing whitespace in README.md

- README.md
- src/Value/CSSFunction.php
- src/Value/Color.php
- src/Value/LineName.php
- src/Value/Value.php
- src/Value/ValueList.php
Replace the list of various possible sub-types with the common ancestor.
Update the class diagram to indicate that `ValueList::$aComponents` no longer has a dependency on the sub-types definitions.
Resolves #499.  Supersedes and closes #506.
> [CLEANUP] Use common ancestor `Value` in type specifications

- README.md
This gets another thing out of the way towards moving to an autogenerated class diagram.
Also sort the moved lines.
> [CLEANUP] Move some things in the class diagram code around

- README.md
This is another step towards auto-generating more of the class diagram.
> [TASK] Use a generated class/diagram list in the class diagram

- README.md
This ends the abstruction of the class diagram.
These typos in the class diagram were caused by a typo in the Mermaid generation tool, which is now fixed.
https://github.com/tasuku43/php-mermaid-class-diagram/releases
> [TASK] Fix typo "abstruct" in the class diagram (again)

- README.md
Now the only part of the class diagram which we need to maintain manually are the associations between classes.
> [TASK] Use auto-generated hierarchy in class diagram

- .github/dependabot.yml
It was nothing fancy; It just calmed my inner Monk, who had been upset about the indentation :)
> [CLEANUP] Fix indentation of dependabot configuration

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
Rewrite the GHA config files using the project style conventions of four spaces as defined in `.editorconfig`.
> [CLEANUP] Fix indentation of GHA configuration

- src/Parsing/ParserState.php
- src/Property/CSSNamespace.php
- src/Property/Import.php
- src/Rule/Rule.php
This applies the rule **AddTestsVoidReturnTypeWhereNoReturnRector**.
For Details see: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#returntypefromstrictnewarrayrector
> [CLEANUP] rector: Add strict return array type based on created empty array and returned

- tests/CSSList/AtRuleBlockListTest.php
- tests/CSSList/DocumentTest.php
- tests/CSSList/KeyFrameTest.php
- tests/Comment/CommentTest.php
- tests/OutputFormatTest.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
- tests/RuleSet/LenientParsingTest.php
- tests/Value/CalcRuleValueListTest.php
This applies the rule **AddTestsVoidReturnTypeWhereNoReturnRector**.
For Details see: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#addtestsvoidreturntypewherenoreturnrector
> [CLEANUP] rector: Add void to PHPUnit test methods

- config/rector.php
This enables the rector rule set for PHP 7.0.
> [TASK] rector: add php70 rule set

- config/rector.php
This way rector always follows the minimal required version in composer.json, which currently is PHP 7.2.
This helps with #433.
> [TASK] rector: set PHP rule-set to the same version as composer.json

- .github/workflows/ci.yml
- composer.json
Also lint `config/` in order to catch e.g. language features that are not supported in all the PHP versions we support.
Fixes: #551
> [TASK] Move linting to a Composer script and use it on CI

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
> [TASK] Remove `DeclarationBlock::setSelector`

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
> [TASK] Remove `DeclarationBlock::getSelector`

- CHANGELOG.md
- src/CSSList/Document.php
> [TASK] Remove `Document::getAllSelectors`

- CHANGELOG.md
- src/Rule/Rule.php
> [TASK] Remove `Rule::setValues`

- CHANGELOG.md
- src/Rule/Rule.php
- tests/ParserTest.php
> [TASK] Remove `Rule::getValues`

- CHANGELOG.md
- src/CSSList/Document.php
> [TASK] Deprecate `Document::createShorthands`

- CHANGELOG.md
- src/CSSList/Document.php
> [TASK] Deprecate `Document::expandShorthands`

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
> [TASK] Deprecate `DeclarationBlock::createShorthands`

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
> [TASK] Deprecate `DeclarationBlock::expandBorderShorthand`

- src/CSSList/AtRuleBlockList.php
- src/CSSList/Document.php
- src/CSSList/KeyFrame.php
- src/Parsing/ParserState.php
- src/RuleSet/DeclarationBlock.php
- src/Value/Size.php
This applies the rule **ReturnTypeFromStrictBoolReturnExprRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#returntypefromstrictboolreturnexprrector
> [CLEANUP] Rector: Add strict return type based on returned strict expr type

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
> [TASK] Deprecate `DeclarationBlock::expandDimensionsShorthand`

- src/Parsing/ParserState.php
This applies the rule **NumericReturnTypeFromStrictScalarReturnsRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#numericreturntypefromstrictscalarreturnsrector
> [CLEANUP] Rector: Change numeric return type based on strict returns type operations

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
> [TASK] Deprecate `DeclarationBlock::expandFontShorthand`

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
> [TASK] Deprecate `DeclarationBlock::expandBackgroundShorthand`

- src/Parsing/ParserState.php
This applies the rule **BoolReturnTypeFromStrictScalarReturnsRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#boolreturntypefromstrictscalarreturnsrector
> [CLEANUP] Rector: Change return type based on strict returns type operations

- src/CSSList/CSSList.php
- src/Parsing/ParserState.php
This applies the rule **ReturnTypeFromStrictTernaryRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#returntypefromstrictternaryrector
> [CLEANUP] Rector: Add method return type based on strict ternary values

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
> [TASK] Deprecate `DeclarationBlock::expandListStyleShorthand`

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
> [TASK] Deprecate `DeclarationBlock::createBackgroundShorthand`

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
> [TASK] Deprecate `DeclarationBlock::createListStyleShorthand`

- src/Parsing/ParserState.php
- src/Rule/Rule.php
- tests/CSSList/DocumentTest.php
- tests/RuleSet/DeclarationBlockTest.php
This applies the rule **ReturnTypeFromReturnDirectArrayRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#returntypefromreturndirectarrayrector
> [CLEANUP] Rector: Add return type from return direct array

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
Helps with fixing https://github.com/MyIntervals/PHP-CSS-Parser/issues/512
> [TASK] Deprecate `DeclarationBlock::createDimensionsShorthand`

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
Helps with fixing https://github.com/MyIntervals/PHP-CSS-Parser/issues/512
> [TASK] Deprecate `DeclarationBlock::createFontShorthand`

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
Helps with fixing https://github.com/MyIntervals/PHP-CSS-Parser/issues/512
> [TASK] Deprecate `DeclarationBlock::createBorderShorthand`

- src/CSSList/Document.php
- src/OutputFormat.php
- src/Parsing/ParserState.php
- src/Rule/Rule.php
- src/Settings.php
- src/Value/CSSString.php
- src/Value/CalcFunction.php
- src/Value/LineName.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/Value.php
This applies the rule **ReturnTypeFromReturnNewRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#returntypefromreturnnewrector
> [CLEANUP] Rector: Add return type to function like with return new

- CHANGELOG.md
- src/CSSList/CSSList.php
- tests/CSSList/DocumentTest.php
This is based on and will supersede #115. Suggestions from the original PR are incorporated, and the initial authorship is preserved.
> [FEATURE] Add support for inserting an item in a CSSList

- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/CSSList/KeyFrame.php
- src/Comment/Comment.php
- src/OutputFormat.php
- src/Parser.php
- src/Parsing/Anchor.php
- src/Parsing/ParserState.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Property/Selector.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/Color.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/ValueList.php
- tests/CSSList/DocumentTest.php
- tests/ParserTest.php
This applies the rule **AddVoidReturnTypeWhereNoReturnRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#addvoidreturntypewherenoreturnrector
> [CLEANUP] Rector: Add return type void to function like without any return

- tests/CSSList/AtRuleBlockListTest.php
- tests/RuleSet/DeclarationBlockTest.php
This applies the rule **AddParamTypeBasedOnPHPUnitDataProviderRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#addparamtypebasedonphpunitdataproviderrector
> [CLEANUP] Rector: Adds param type declaration based on PHPUnit provider return type declaration

- src/OutputFormatter.php
This applies the rule **ReturnTypeFromStrictNativeCallRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#returntypefromstrictnativecallrector
> [CLEANUP] Rector: Add strict return type based native function or class method return

- tests/RuleSet/LenientParsingTest.php
This avoids the "This test did not perform any assertions" warning from PHPUnit.
> [CLEANUP] Ensure all tests actually have an assertion

- src/Value/CSSFunction.php
- src/Value/CalcFunction.php
- src/Value/Color.php
Also
- Update the `parse` function signature to use PHP7 type hints;
- Remove subsequently redundant DocBlock entries;
- Ditto for same-named method in subclass to avoid contravariance.
This is the refactoring change from #390.
> [CLEANUP] Extract CSSFunction methods parseName and parseArguments

- .github/workflows/ci.yml
This is a pre-patch before we can switch the PHP linting to the parallel lint package in #610.
> [TASK] Install Composer dependencies for PHP lint CI job

- composer.json
Use `php-parallel-lint` package to avoid *nix-specific command.
Fixes #598.
> [BUGFIX] Support Lint on Windows

- CHANGELOG.md
- src/Value/Value.php
- tests/Value/ValueTest.php
This is the enhancement from #390.
> [FEATURE] Support arithmetic operators in CSS functions

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/Value/CalcFunction.php
This is the 8.x backport of #593.
Fixes #585
> [BUGFIX] Fix undefined local variable in `CalcFunction::parse()`

- src/CSSList/AtRuleBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/KeyFrame.php
- src/Comment/Comment.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Property/Selector.php
- src/Rule/Rule.php
- src/RuleSet/AtRuleSet.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/Color.php
- src/Value/LineName.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/ValueList.php
This applies the rule **AddReturnTypeDeclarationBasedOnParentClassMethodRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#addreturntypedeclarationbasedonparentclassmethodrector
> [CLEANUP] Rector: Add missing return type declaration based on parent class method

- tests/Value/ValueTest.php
In the test cases added so far, this doesn't seem to affect results, but would be needed for tests that may be added in future to ensure consistencey with how the method is actually used at runtime.
> [BUGFIX] Provide the usual set of delimiters in parseValue tests

- tests/Value/ValueTest.php
Closes #619.
The test passes, whereas without the change from #607, it does not.
> [TASK] Test parsing arithmetic operators in clamp function

- CHANGELOG.md
- src/Value/Size.php
- tests/Value/SizeTest.php
Fixes #412
For now, the `TestCase` just tests that all the unit values are parsed. (Other tests can be added here, but are beyond the scope of this change.)
> [FEATURE] Add support for the `dvh`, `lvh` and `svh` length units (#415)

- CHANGELOG.md
- src/Value/Value.php
When there are many many elements in $aStack, starting the delimiter search from the beginning for each loop is very very slow. I addressed this by building a new array rather than modifying $aStack in place and iterating over it in a single pass. The particular 1.6M style string that was giving me trouble went from taking 4 minutes to parse to 5 seconds.
> [TASK] Avoid poor scaling of array_search() with very long arrays (#413)

- .gitattributes
- .github/CONTRIBUTING.md
- CODE_OF_CONDUCT.md
This is the first part of #489.
I'd like to add sections bit by bit to make reviewing easier and faster, and to allow us to get things online quickly.
This file will be in sync with its counterpart in the Emogrifier project as much as possible.
> [TASK] Start the contributor guidelines with the CoC

- CHANGELOG.md
- src/Value/Value.php
- tests/Value/ValueTest.php
This is the enhancement from #390.
`calc` was already supported.
> [FEATURE] Support arithmetic operators in CSS functions (#607)

- CHANGELOG.md
There don't seem to be any more enhancements in the immediate pipeline, so it would be good to get this out now with the four we have, most or all of which I think have been requested by users.
(I'm not sure I can do the actual release.  I've never made one before, and don't know what's involved/needed.)
> [TASK] Prepare the 8.6.0 release

- bin/quickdump.php
- src/CSSList/CSSBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/OutputFormat.php
- src/OutputFormatter.php
- src/Parsing/ParserState.php
- src/Parsing/UnexpectedTokenException.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Property/Selector.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Settings.php
- src/Value/CSSString.php
- src/Value/CalcFunction.php
- src/Value/Color.php
- src/Value/Size.php
- src/Value/Value.php
- src/Value/ValueList.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
- tests/RuleSet/LenientParsingTest.php
- tests/SettingsTest.php
This slightly improves performance.
> [TASK] Prefix native function calls with a backslash

- src/CSSList/Document.php
- src/OutputFormatter.php
This was done using the `phpdoc_trim` PHP-CS-Fixer rule.
> [TASK] Drop surplus empty lines from PHPDoc

- src/CSSList/CSSList.php
This was done using the `phpdoc_types_order` PHP-CS-Fixer rule.
> [CLEANUP] Sort the types in union type PHPDoc annotations

- src/Parsing/ParserState.php
- src/Property/KeyframeSelector.php
- src/Property/Selector.php
- src/Value/CSSString.php
- src/Value/Size.php
- src/Value/Value.php
- tests/ParserTest.php
This was done using the `string_implicit_backslashes` PHP-CS-Fixer rule.
> [CLEANUP] Always escape backslashes in strings

- config/php-cs-fixer.php
Also drop some rules that are already in included in the used
rulesets.
> [TASK] Add more PHP-CS-Fixer rules

- config/php-cs-fixer.php
- src/CSSList/CSSList.php
- src/OutputFormat.php
- src/Parsing/ParserState.php
- src/Property/Import.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSString.php
- src/Value/Size.php
- src/Value/Value.php
- tests/OutputFormatTest.php
- tests/ParserTest.php
- tests/RuleSet/LenientParsingTest.php
> [CLEANUP] Use single-quoted string literals whenever possible

- config/php-cs-fixer.php
- src/CSSList/Document.php
- src/Parser.php
- src/RuleSet/RuleSet.php
Ensure that parameters that have a `null` default value also have `null` as part of their type declarations.
Also ensure a uniform notation for nullable types.
https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated
Fixes #634
> [TASK] Ensure PHP 8.4 compatibility for nullable parameters

- config/php-cs-fixer.php
It is now listed in the correct section.
Also, as we're using the default configuration for this rule, we can use `true` for this instead of duplicating the default configuration.
> [CLEANUP] Move the `nullable_type_declaration` rule

- CODE_OF_CONDUCT.md
Copy version 2.1 of the contributor convenant code of conduct without any changes except those:
- use our contact email address
- drop links additional resources related to the contributor covenant CoC
https://www.contributor-covenant.org/version/2/1/code_of_conduct/
> [TASK] Update the code of conduct to version 2.1

- CHANGELOG.md
- src/Rule/Rule.php
- tests/ParserTest.php
Because of an eager consumption of whitespace, the rule parsing would swallow a trailing comment, meaning the comment for the next rule would be affected. This patch addresses this by only consuming real whitespace without comments after a rule.
Fixes #173
> [BUGFIX] Fix comment parsing to support multiple comments (backported)

- CHANGELOG.md
- src/Rule/Rule.php
- tests/ParserTest.php
Because of an eager consumption of whitespace, the rule parsing would swallow a trailing comment, meaning the comment for the next rule would be affected. This patch addresses this by only consuming real whitespace without comments after a rule.
Fixes #173
> [BUGFIX]  Fix comment parsing to support multiple comments

- .github/CONTRIBUTING.md
> [TASK] Document the general contribution workflow

- tests/CSSList/DocumentTest.php
- tests/CSSList/KeyFrameTest.php
- tests/OutputFormatTest.php
If we want to work both with PHPUnit 5.x and 8.x, we cannot use PHPUnit's `setUp()` method: This method would need to have a `: void` return type declaration for PHPUnit 8.x, which is not possible with PHP 5.6 (the lowest version we support).
> [BUGFIX] Avoid using `setUp()` in testcases

- phpunit.xml
We still want to require the `@covers` annotation to be used for testcase (`forceCoversAnnotation="true"`), but we also want to be able to indirectly execute code that is not referenced via an `@covers` annotation.
> [TASK] Be less strict about the `@covers` annotation

- .github/workflows/codecoverage.yml
- .gitignore
- README.md
- composer.json
- phpunit.xml
Coveralls does not require an API key, provides a nice GitHub Action, and it can post code coverage comments to PRs.
Also add a code coverage badge to the README.
Also align the GitHub Action workflow with that of our sister project Emogrifier.
Also add a Composer script for running the tests with coverage.
Fixes #535
Fixes #299
> [TASK] Switch our code coverage CI from Codacy to Coveralls

- CHANGELOG.md
- src/Value/Size.php
- tests/ParserTest.php
> [BUGFIX] Fix type errors in PHP strict mode

- composer.json
This hopefully will allow us to run the unit tests for all PHP version that we claim to support, i.e., from 5.6.x to currently 8.4.x.
> [TASK] Also allow higher versions of PHPUnit

- .github/workflows/codecoverage.yml
As we don't have any direct production dependencies, it does not make sense to test both with highest and lowest Composer versions on CI.
We accidentally added this highest/lowest switch with the new coverage job. This commit removes this again, allowing for sharing the Composer caches with the main CI job.
> [TASK] Drop the highest/lowest Composer version switch

- CHANGELOG.md
- src/Parser.php
> [TASK] Deprecate `Parser::setCharset()` and `Parser::getCharset()`

- composer.json
We don't want to have sudden build failures when a new version of a development dependency gets released.
Instead, we'll keep having automatic Dependabot updates for our dependencies that will allow us to see the effects of each update before switchting to a new version of a dependency.
> [TASK] Use fixed versions of the development dependencies

- CHANGELOG.md
- src/Parsing/Anchor.php
- src/Parsing/ParserState.php
Code that uses this library is not expected to call internal parsing functionality. Communicate this with the corresponding `@internal` annotation.
This allows us to boldly refactor the parser code.
This is the backport of #674.
Part of #668
> [TASK] Mark parsing-internal classes and methods as `@internal`

- src/CSSList/Document.php
- src/RuleSet/DeclarationBlock.php
This will allow us to get rid of the code earlier, which will reduce code complexity and make maintenance easier.
I will backport those deprecations to 8.x.
> [TASK] Mark the shorthand expansion as to be removed earlier

- .gitattributes
- CHANGELOG.md
- README.md
- docs/API-and-deprecation-policy.md
As discussed here:
https://github.com/MyIntervals/PHP-CSS-Parser/discussions/715
> [DOCS] Add an API and deprecation policy

- src/CSSList/Document.php
- src/Parser.php
- src/Parsing/Anchor.php
- src/Parsing/ParserState.php
- src/Property/AtRule.php
- src/Property/KeyframeSelector.php
- src/Property/Selector.php
- src/RuleSet/DeclarationBlock.php
This will help us avoid breaking things in backports.
This is the v8.x backport of #722.
> [TASK] State since which version code is `@internal`/`@deprecated`

- src/Comment/Comment.php
This change does not include any breaking changes.
> [TASK] Avoid Hungarian notation in a class

- composer.json
This avoids build breakage when a new version of PHPUnit gets released.
> [TASK] Use fixed PHPUnit versions

- src/Parsing/OutputException.php
- src/Parsing/UnexpectedEOFException.php
This pull request addresses issue [#709](https://github.com/MyIntervals/PHP-CSS-Parser/issues/709) by marking certain exception classes final in the `src/Parsing` directory. 
The most important changes are as follows:
Class modifications:
* `src/Parsing/OutputException.php`: Changed the `OutputException` class to be final.
* `src/Parsing/UnexpectedEOFException.php`: Changed the `UnexpectedEOFException` class to be final.
Note: 
* skipped `SourceException` because `OutputException` extends `SourceException`
* skipped `UnexpectedTokenException` because `UnexpectedEOFException` extends `UnexpectedTokenException`
> Mark Exception Classes as Final

- .github/workflows/require-tests.yml
This pull request addresses issue [#729](https://github.com/MyIntervals/PHP-CSS-Parser/issues/729) by adding the  [infection/tests-checker-action](https://github.com/infection/tests-checker-action) GitHub Action that ensures tests are included in pull requests.
Changes Introduced:
- `.github/workflows/require-tests.yml`: Added a workflow named 'Require Tests' that uses the `infection/tests-checker-action` to verify the presence of test files in the `tests` directory with a specific pattern (`*Test.php`).
> Add GitHub Action to Require Tests in Pull Requests

- tests/RuleSet/DeclarationBlockTest.php
Also add a skipped test for the broken behavior that currently
is blocking Emogrifier.
> [TASK] Add some more tests for parsing comments

- CHANGELOG.md
- src/Rule/Rule.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
This reverts e4c66f62c5df3f53f48d82cb30b20b3007af7574 (#672), which broke comment parsing in strict mode.
We'll need to re-implement support for multiple comments later in a way that does not break the existing comment parsing.
> [BUGFIX] Revert broken support for multiple comments

- CHANGELOG.md
- src/CSSList/AtRuleBlockList.php
- src/CSSList/Document.php
- src/CSSList/KeyFrame.php
- src/Comment/Comment.php
- src/Parser.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Renderable.php
- src/Rule/Rule.php
- src/RuleSet/AtRuleSet.php
- src/RuleSet/DeclarationBlock.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/CalcRuleValueList.php
- src/Value/Color.php
- src/Value/LineName.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/ValueList.php
This avoids deprecation warnings in PHP 8.4.
Unfortunately, we need to remove the native type declaration for this to keep supporting PHP down to version 5.6.
> [BUGFIX] Avoid implicit nullable parameters

- phpunit.xml
This change brings the PHPUnit configuration in line with what we have at Emogrifier (except for the difference in the XSD version number).
> [TASK] Configure PHPUnit to be more strict

- CHANGELOG.md
This allows autoformatting the changelog after adding new entries possible without introducing unrelated changes.
This is the v8.x backport of #718.
> [CLEANUP] Autoformat the changelog

- CHANGELOG.md
- src/RuleSet/RuleSet.php
This fixes compatibility with PHP 8.4.
This is the last part of the v8.x backport of #643.
> [BUGFIX] Fix another implictly nullable parameter

- CONTRIBUTING.md
This change copies the corresponding section from our sister project.
> [DOCS] Explain code reviews in `CONTRIBUTING.md`

- composer.json
This makes our life as developers a bit more convenient.
Also run Rector before the style fixer as Rector is responsible for structural changes that need to be style-fixed after that.
> [TASK] Add a `fix` Composer script to run all code fixers

- .github/workflows/ci.yml
Following this change in Emogrifier and preparing for the addition of composer-normalize:
https://github.com/MyIntervals/emogrifier/pull/1363
> [TASK] Prepare for non-PHP-checks on CI

- CONTRIBUTING.md
This change mirrors exactly what we already have at our sister project.
> [DOCS] Add a section on testing to `CONTRIBUTING.md`

- CONTRIBUTING.md
This is an exact copy of what we have at our sister project.
> [TASK] Add a section on coding style to `CONTRIBUTING.md`

- src/CSSList/CSSList.php
- src/OutputFormat.php
- src/OutputFormatter.php
- src/Parsing/Anchor.php
- src/Parsing/ParserState.php
- src/RuleSet/RuleSet.php
- src/Settings.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/Color.php
Just the Rector changes, and some redundancy removal related to those, but nothing more.
> [TASK] Clean up the code with Rector

- composer.json
We're not there yet, but we want to be prepared for when we are.
This follows what we have in our sister project.
> [TASK] Allow generating an empty PHPStan baseline

- config/phpstan.neon
`scanDirectories` is not needed when `paths` is set.
> [TASK] Drop redundant PHPStan configuration options

- tests/Unit/Value/ColorTest.php
This covers expected behaviour for CSS level 3
(some of which is also covered by more general tests).
Also included are some commented-out tests for CSS Color Module Level 4, support for which is yet to be implemented,
as well as for some syntaxes that should be rejected (but currently are not).
Precursor to resolving #755 and supporting CSS Color Module Level 4.
> [TASK] Add TestCase for `Value\Color`

- CHANGELOG.md
- src/Rule/Rule.php
- tests/Unit/Rule/RuleTest.php
Fixes #789.
Also adds an initial `TestCase` for `Rule/Rule`.
This is the 8.x backport of #790.
> [BUGFIX] Parse `@font-face` src property as comma-delimited list

- config/php-cs-fixer.php
Unfortunately, this has been broken for comments preceding a `case` within a `switch` since PHP CS Fixer version 3.9.1.
See
- https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6572
- https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6490
- https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6490#issuecomment-1874110032
- https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7624
A configuration option `stick_comment_to_next_continuous_control_statement` was added, but this has not yet been extended to cover `case` within a `switch`.
So, for the time being, we cannot use this rule if we want to comment `case`s within a `swtich`.
> [TASK] Disable PHP CS Fixer `statement_indentation` rule

- CHANGELOG.md
- src/Value/Color.php
- tests/Unit/Value/ColorTest.php
As of CSS Color Module Level 4, `rgba` is an alias of `rgb`; likewise, `hsla` is an alias of `hsl`.
This change allows any of the above color functions to contain either three or four arguments, with alpha assumed as the fourth, and allowed to be absent.
> [FEATURE] Support rgba and rgb (etc.) being aliases

- CHANGELOG.md
- src/Value/Color.php
- tests/Unit/Value/ColorTest.php
Also include tests for color functions with CSS variable substitutions where they use the "legacy" syntax.
Resolves #755.
> [FEATURE] Parse color functions with modern syntax

- src/Value/Color.php
Also rename some variables to be more descriptive and/or avoid abbreviations.
> [CLEANUP] Avoid Hungarian notation in `Color` class

- CHANGELOG.md
- src/Value/Color.php
- tests/Unit/Value/ColorTest.php
The only percentage values that could be reliably converted to hex notation are 0%, 20%, 40%, etc.
It's beyond the scope of this library to do that.
Also add additional tests to confirm parsing of percentage values. Some of these are commented out, because the input data would result in rendering in an invalid format. (The "legacy" syntax does not allow a mixture of `percentage`s and `number`s, so it would be necessary to implement rendering in the "modern" syntax to resolve those cases, which is beyond the scope of this PR.)
> [BUGFIX] Don't render `rgb` colors with `%` values as hex

- src/CSSList/CSSList.php
- src/Comment/Commentable.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Rule/Rule.php
- src/RuleSet/RuleSet.php
Also adapt the implementing classes accordingly.
Part of #756.
> [CLEANUP] Avoid Hungarian notion for the `Commentable` interface

- CHANGELOG.md
- src/CSSList/CSSBlockList.php
- src/Comment/Commentable.php
- src/Property/Charset.php
- src/Property/Selector.php
- src/Rule/Rule.php
Also include previous changes for adding native type declarations or strict mode into the changelog.
> [TASK] Use native `void` return type declarations

- README.md
We now have instructions on testing in `CONTRIBUTING.md`.
> [DOCS] Remove section on testing from `README.md`

- CHANGELOG.md
- src/Parser.php
These methods were deprecated in version 8.7.0.
Fixes #687
> [TASK] Remove `Parser::setCharset/getCharset`

- src/CSSList/AtRuleBlockList.php
> [CLEANUP] Avoid Hungarian notation in `AtRuleBlockList`

- src/CSSList/CSSBlockList.php
> [TASK] Avoid Hungarian notation in `CSSBlockList`

- tests/Comment/CommentTest.php
- tests/Unit/Comment/CommentTest.php
> [TASK] Migrate part of `CommentTests` to unit tests

- tests/fixtures/-fault-tolerance.css
- tests/fixtures/1readme.css
- tests/fixtures/2readme.css
- tests/fixtures/atrules.css
- tests/fixtures/calc.css
- tests/fixtures/case-insensitivity.css
- tests/fixtures/colortest.css
- tests/fixtures/escaped-tokens.css
- tests/fixtures/ie.css
- tests/fixtures/inner-color.css
- tests/fixtures/missing-property-value.css
- tests/fixtures/namespaces.css
- tests/fixtures/nested.css
- tests/fixtures/slashed.css
- tests/fixtures/specificity.css
- tests/fixtures/url.css
- tests/fixtures/values.css
- tests/fixtures/whitespace.css
This makes editing the fixture files a bit easier as all other files in this project also use spaces for indentation, not tabs.
Note: This has no effect on CSS is rendered (which still defaults to tabs at the moment).
> [CLEANUP] Use spaces for indenting the fixture CSS files

- config/phpstan-baseline.neon
- tests/ParserTest.php
- tests/RuleSet/LenientParsingTest.php
According to the PHPUnit documentation [1], `@covers` annotations are only recommended to reference classes (and global functions), but not methods from classes.
Also sort the `@covers` annotations.
Note: This will probably artificially increase our calculated code coverage numbers until we migrate our tests to more focused unit tests.
Closes #809
[1] https://docs.phpunit.de/en/8.5/annotations.html#covers
> [TASK] Avoid using `@covers` annotations referencing methods

- src/Value/Color.php
An additional method to render in the "modern" syntax will soon be needed. Splitting up the `render` method into sub-methods will help as a precursor to that.
> [CLEANUP] Extract method `Color::renderAsHex`

- CHANGELOG.md
- src/RuleSet/DeclarationBlock.php
This is the v8.x backport of #814.
> [BUGFIX] Create `Size` with correct types in `expandBackgroundShorthand`

- CHANGELOG.md
Now the changelog up to the latest feature release 8.7.0 is part of the `main` changelog.
This makes it easier to see what has changed after the last feature release.
Also, this makes it clear in which release some methods were deprecated, avoid the impression that methods got both deprecated and removed in the same release.
Also autoformat the changelog.
> [DOCS] Integrate the `8.x` changelog into the `main` changelog

- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/Parser.php
- src/Parsing/Anchor.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/CalcFunction.php
- src/Value/LineName.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/Value.php
> [CLEANUP] Avoid Hungarian notation for `oParserState`

- src/CSSList/CSSBlockList.php
- src/Rule/Rule.php
- src/RuleSet/RuleSet.php
> [CLEANUP] Avoid Hungarian notation for `oRule`/`oRuleSet`

- CHANGELOG.md
- src/CSSList/CSSList.php
- src/RuleSet/RuleSet.php
Also make then static if possible.
> [TASK] Add native type declarations for anonymous functions

- src/CSSList/CSSList.php
- src/OutputFormatter.php
- src/Parsing/ParserState.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
> [CLEANUP] Avoid Hungarian notation for `aComments`

- CHANGELOG.md
- src/Value/Color.php
- tests/Unit/Value/ColorTest.php
The "legacy" syntax does not allow a mixture of `percentage`s and `number`s for the red, green and blue components.
So if `rgb`/`rgba` functions that have such a mixture are rendered in the "legacy" syntax, an invalid property value will result.
An `OutputFormat` option to use the "modern" syntax throughout will be added later (see #801).
> [BUGFIX] Render RGB functions with "modern" syntax if required

- src/CSSList/CSSBlockList.php
> [CLEANUP] Avoid Hungarian notation in `CSSBlockList` (part 2)

- src/Value/Color.php
> [CLEANUP] Extract method `Color::shouldRenderAsHex`

- src/CSSList/CSSBlockList.php
- src/CSSList/CSSList.php
> [CLEANUP] Avoid Hungarian notation for `aContents` and items

- src/CSSList/CSSList.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
> [CLEANUP] Avoid Hungarian notation for `iKey`

- src/Rule/Rule.php
- src/Value/Color.php
- tests/ParserTest.php
- use paranthesis for negated `instanceof` calls
- use `assertInstanceOf` in the tests
> [CLEANUP] Improve readability of `instanceof` calls

- src/CSSList/CSSList.php
- src/RuleSet/DeclarationBlock.php
- src/Value/CalcFunction.php
- src/Value/Value.php
> [CLEANUP] Avoid Hungarian notation for `oList` and `oListItem`

- tests/Unit/OutputFormatTest.php
Currently, this class uses magic getters and setters. These
should be proper methods instead.
But first, we should have tests for the accessors. This is
part 1.
> [TASK] Add accessor tests for `OutputFormat` (part 1)

- CHANGELOG.md
- src/Value/Color.php
- tests/Unit/Value/ColorTest.php
Note that this keyword is only permitted in the "modern" syntax (and thus functions using it must be rendered in that syntax).
> [FEATURE] Support `none` as color function component value

- src/CSSList/CSSList.php
- src/Settings.php
Keep the name of the public property in `Settings` unchanged, though, as it currently probably is part of the API.
Part of #756.
> [CLEANUP] Avoid Hungarian notation for `bLenientParsing`

- tests/Unit/OutputFormatTest.php
Currently, this class uses magic getters and setters. These should be proper methods instead.
But first, we should have tests for the accessors. This is part 2.
> [TASK] Add accessor tests for `OutputFormat` (part 2)

- src/CSSList/CSSList.php
- src/Property/Import.php
> [CLEANUP] Avoid Hungarian notation for `oLocation`

- src/CSSList/CSSList.php
- src/RuleSet/DeclarationBlock.php
- src/Value/CSSFunction.php
- src/Value/URL.php
> [CLEANUP] Avoid Hungarian notation for `oResult`

- src/CSSList/CSSList.php
> [CLEANUP] Avoid Hungarian notation in `CSSList`

- CHANGELOG.md
- src/OutputFormat.php
Also improve the naming of the parameters.
> [TASK] Add type declarations for `OutputFormat::indentWith*`

- CHANGELOG.md
- src/OutputFormat.php
- src/OutputFormatter.php
- tests/Unit/OutputFormatTest.php
This method is an inconsistently-named alias of
`OutputFormat::getIndentationLevel()`.
Fixes #869
> [TASK] Remove the deprecated `OutputFormat::level()`

- CHANGELOG.md
- src/OutputFormat.php
Also fix some type annotations.
> [TASK] Add native type declarations to `OutputFormat`

- CHANGELOG.md
- src/OutputFormat.php
- src/OutputFormatter.php
- tests/OutputFormatTest.php
- tests/Unit/OutputFormatTest.php
`SpaceBeforeListArgumentSeparators` and `SpaceAfterListArgumentSeparators` are added to allow for different spacing for different separators.
`SpaceBeforeListArgumentSeparator` and `SpaceAfterListArgumentSeparator` will specify the default spacing.  Setting these as an array is deprecated.
Resolves #866, #876, #878.
> [CLEANUP] Add separate `OutputFormat` properties for arrays

- CHANGELOG.md
- src/CSSList/CSSList.php
- src/Comment/Comment.php
- src/OutputFormat.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Rule/Rule.php
- src/RuleSet/RuleSet.php
- src/Settings.php
- src/Value/CSSFunction.php
- src/Value/Value.php
- src/Value/ValueList.php
This communicates clearly that the properties may be removed, renamed or made `private` at any point, and that they should not be accessed directly, but using the accessors instead.
Also add a type annotation that was missing.
Fixes #881
> [TASK] Make all non-private properties `@internal`

- CHANGELOG.md
- src/OutputFormat.php
- tests/OutputFormatTest.php
`sBeforeAfterListArgumentSeparator` and
`sSpaceAfterListArgumentSeparator` now can only hold strings, and no longer arrays (which was deprecated in V8.8.0).
> [TASK] Only allow `string` for some `OutputFormat` properties

- src/Value/CSSFunction.php
This is the V8.x backport of #897.
> [BUGFIX] Add missing imports for `@throws` annotations

- CHANGELOG.md
- src/OutputFormat.php
This method is used internally for rendering the CSS, and it is not intended to be called from outside this library.
> [TASK] Mark `OutputFormat::nextLevel()` as `@internal`

- src/OutputFormat.php
This is the V8.x backport of #902.
> [BUGFIX] Fix an incorrect type annotation in `OutputFormat`

- src/CSSList/AtRuleBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/CSSList/KeyFrame.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Renderable.php
- src/Rule/Rule.php
- src/RuleSet/AtRuleSet.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/CalcRuleValueList.php
- src/Value/LineName.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/ValueList.php
> [CLEANUP] Avoid Hungarian notation for `outputFormat`

- composer.json
- config/phpstan-baseline.neon
Now we are using the same static analysis tools as our sister project.
> [TASK] Add strict PHPStan rules

- CHANGELOG.md
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/Parsing/ParserState.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/CalcFunction.php
- src/Value/Color.php
- src/Value/LineName.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/Value.php
The only parsing method that is expected to be called from outside of this library is `Parser::parse()`.
> [TASK] Mark many parsing-related methods as `@internal`

- tests/Functional/Comment/CommentTest.php
- tests/Unit/Comment/CommentTest.php
Move the tests that rely on another class (`OutputFormat`) (or might in the future).
Part of #757.
> [TASK] Move some tests for `Comment` to functional tests

- tests/Unit/Parsing/OutputExceptionTest.php
- tests/Unit/Parsing/SourceExceptionTest.php
- tests/Unit/Parsing/UnexpectedEOFExceptionTest.php
- tests/Unit/Parsing/UnexpectedTokenExceptionTest.php
> [TASK] Add tests for the exceptions

- src/CSSList/AtRuleBlockList.php
- src/RuleSet/AtRuleSet.php
> [CLEANUP] Avoid Hungarian notation for `arguments`

- src/CSSList/AtRuleBlockList.php
- src/CSSList/Document.php
- src/CSSList/KeyFrame.php
- src/OutputFormatter.php
- src/Parsing/ParserState.php
- src/Property/CSSNamespace.php
- src/Property/Import.php
- src/Rule/Rule.php
- src/RuleSet/AtRuleSet.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSString.php
- src/Value/Value.php
> [CLEANUP] Avoid Hungarian notation for `result`

- src/CSSList/CSSList.php
- src/OutputFormat.php
- src/Property/CSSNamespace.php
> [CLEANUP] Avoid Hungarian notation for `prefix`

- src/OutputFormat.php
- tests/Unit/OutputFormatTest.php
Also add one more test for good measure.
> [TASK] Use type-safe setters in `OutputFormat` factory methods

- tests/Unit/CSSList/DocumentTest.php
Also fix some type annotation for the moved tests.
Part of #758
> [TASK] Move `DocumentTest` to unit tests

- src/CSSList/CSSBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/CSSList/KeyFrame.php
- src/OutputFormat.php
- src/Parsing/ParserState.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/PrimitiveValue.php
- use default values for properties instead of setting them in the constructor
- drop constructors that are redundant to the constructor of the parent class
> [TASK] Drop redundant constructor code

- src/CSSList/Document.php
> [CLEANUP] Avoid Hungarian notation in `Document`

- tests/Unit/CSSList/AtRuleBlockListTest.php
> [TASK] Add some more unit tests for `AtRuleBlockList`

- src/Parsing/Anchor.php
- src/Parsing/ParserState.php
- src/RuleSet/RuleSet.php
> [CLEANUP] Avoid Hungarian notation for `position`

- composer.json
- config/phpstan-baseline.neon
- config/phpstan.neon
This is an opiniated set of PHPStan rules to make code more explicit and intuitive to read.
https://github.com/rectorphp/type-perfect
The new rules show some parts where we could improve our code, which have now been added to the PHPStan baseline.
> [TASK] Add PHPStan rules from Rector Type Perfect

- src/Parsing/ParserState.php
As this class is `@internal`, we do not need a deprecation process for this.
> [TASK] Drop the unused `ParserState::getCharset()`

- src/OutputFormat.php
- src/OutputFormatter.php
> [CLEANUP] Avoid Hungarian notation for `outputFormat(ter)`

- src/Parser.php
- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `text`/`characters`

- config/phpstan-baseline.neon
- tests/Unit/OutputFormatterTest.php
Note: The new PHPStan warnings will go away once we add
native type declarations for `OutputFormatter`.
Part of #757
> [TASK] Add some tests for `OutputFormatter` (part 1)

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `currentPosition`

- src/Parsing/ParserState.php
- src/Property/Charset.php
> [CLEANUP] Avoid Hungarian notation for `charset`

- src/Parsing/ParserState.php
If a whole class is `@internal`, there is no need to mark the individual methods, properties or constants as `@internal`.
> [CLEANUP] Drop redundant `@internal` annotations

- tests/Unit/CSSList/AtRuleBlockListTest.php
This makes the test easier to read. Also, this prepares for when an `AtRuleBlockList` might not allow an empty type anymore.
> [TASK] Use more real-life data in a unit test

- src/Parsing/ParserState.php
- src/Value/CSSFunction.php
- src/Value/CalcFunction.php
- src/Value/Value.php
> [CLEANUP] Avoid Hungarian notation for `ignoreCase`

- config/phpstan-baseline.neon
- tests/Unit/OutputFormatterTest.php
Also autoformat the test class.
The new PHPStan warning will go away once we switch the tested class to native type declarations.
Part of #757
> [TASK] Add some tests for `OutputFormatter` (part 2)

- src/Parsing/ParserState.php
... by throwing an exception on failure.
> [CLEANUP] Ensure `ParserState::strsplit()` always returns array

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `character`

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `isForIdentifier`

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/OutputFormat.php
- src/OutputFormatter.php
Also improve a related type annotation.
Part of #811.
> [TASK] Use native type declarations in `OutputFormatter`

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation in `parseCharacter()`

- src/OutputFormatter.php
Avoid direct access to `OutputFormat` properties as well as variable access and magic methods.
Also drop some dead code.
We might possibly want to drop the `space` method altogether, but that's out of scope for this change.
> [CLEANUP] Use accessors in `OutputFormatter`

- src/CSSList/Document.php
- tests/Unit/CSSList/DocumentTest.php
Also remove a misleading and incorrect comment.
Part of #757
> [TASK] Add Tests for `Document::getAllDeclarationBlocks()`

- src/OutputFormatter.php
- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `comment(able)`

- src/Parsing/ParserState.php
Since PHP 5, if not earlier, the length of an array is internally stored by PHP and can be accessed in O(1) time.
Maintaining both the array and its length in class properties is error-prone (particularly regarding possible future code changes). When used in a loop, `\count($array)` is more repetitively expensive than `$arrayLength`,
but the latter can be set up as a local variable as and when needed.
Reference:
https://stackoverflow.com/questions/5835241/is-phps-count-function-o1-or-on-for-arrays
This change also ensures that the characters are always a (dazzling) array.
Resolves #953.
> [CLEANUP] Don't store array length as a property

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `caseInsensitive`

- src/Parsing/ParserState.php
- src/Value/Value.php
> [CLEANUP] Avoid Hungarian notation for `start(Position)`

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation in `ParserState`

- src/Property/Charset.php
> [CLEANUP] Avoid Hungarian notation in `Charset`

- src/Property/CSSNamespace.php
> [CLEANUP] Avoid Hungarian notation in `CSSNamespace`

- tests/Unit/Value/CalcRuleValueListTest.php
Also add the missing `@covers` annotations for the superclasses of the tested class.
Part of #758.
> [TASK] Move `CalcRuleValueListTest` to unit tests

- config/phpstan-baseline.neon
- src/RuleSet/DeclarationBlock.php
The variable is either a string or it isn't.
The best practice for when it isn't is for it to be `null` or `unset()`.
Using `false` for when it isn't can lead to type-safety issues. Reference:
https://vulke.medium.com/when-should-variables-be-null-false-undefined-or-an-empty-string-in-php-4ebd73c7a954
Also use `===` in a comparison in the affected code.
Resolves #975.
Part of #976.
> [CLEANUP] Use `null` for unset value in `DeclarationBlock::parse()`

- src/Property/Selector.php
> [CLEANUP] Avoid Hungarian notation for `selector`

- src/Property/Selector.php
> [CLEANUP] Avoid Hungarian notation in `Selector`

- tests/Unit/CSSList/AtRuleBlockListTest.php
- tests/Unit/CSSList/DocumentTest.php
- tests/Unit/CSSList/KeyFrameTest.php
These comments are no longer needed now that the abstract base classes have their own testcases.
> [CLEANUP] Drop some comments from testcases

- src/Rule/Rule.php
> [CLEANUP] Avoid Hungarian notation in `Rule`

- tests/Unit/CSSList/DocumentTest.php
> [TASK] Add tests for `Document::getAllRuleSets()`

- src/RuleSet/AtRuleSet.php
> [CLEANUP] Avoid Hungarian notation in `AtRuleSet`

- config/phpstan-baseline.neon
- tests/Unit/Value/CSSStringTest.php
> [TASK] Add some basic tests for `CSSString`

- src/CSSList/CSSList.php
- src/Parsing/ParserState.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Settings.php
- src/Value/LineName.php
- src/Value/Value.php
- tests/Unit/SettingsTest.php
We'll change the direct accesses to use the accessors in a later chance.
Part of #756
> [CLEANUP] Avoid Hungarian notation in `Settings`

- CHANGELOG.md
- src/CSSList/AtRuleBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/KeyFrame.php
- src/Comment/Comment.php
- src/OutputFormatter.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Property/Selector.php
- src/Renderable.php
- src/Rule/Rule.php
- src/RuleSet/AtRuleSet.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSFunction.php
- src/Value/CSSString.php
- src/Value/Color.php
- src/Value/LineName.php
- src/Value/Size.php
- src/Value/URL.php
- src/Value/ValueList.php
- tests/Functional/Comment/CommentTest.php
- tests/FunctionalDeprecated/Comment/CommentTest.php
> [TASK] Deprecate `__toString()`

- src/CSSList/CSSBlockList.php
> [CLEANUP] Refactor `::getAllDeclarationBlocks()`

- src/CSSList/CSSList.php
- src/Parsing/ParserState.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Settings.php
- src/Value/LineName.php
- src/Value/Value.php
- tests/Unit/SettingsTest.php
Also make a type annotation more specific along the way.
> [FEATURE] Add internal getters to `Settings` and use them

- CHANGELOG.md
- src/Property/Selector.php
This constructor parameter is not used, and having the specificity calculation always done lazily is not a problem.
> [TASK] Deprecate greedy calculation of selector specificity

- src/RuleSet/RuleSet.php
> [CLEANUP] Avoid Hungarian notation for `rules`

- src/OutputFormat.php
- src/RuleSet/RuleSet.php
> [CLEANUP] Avoid Hungarian notation for `nextLevelFormat`

- src/RuleSet/RuleSet.php
> [CLEANUP] Avoid Hungarian notation for `searchPattern`

- src/RuleSet/RuleSet.php
> [CLEANUP] Avoid Hungarian notation for `consumedText`

- CHANGELOG.md
- src/Renderable.php
The concept of being able to get rendered is logically independent from having a position in the input stream.
Hence, both concepts should not be intermingled in the `Renderable` interface.
(We might want to add a dedicated interface for classes that are linked to specific points in the input stream later, though.)
> [TASK] Drop `getLineNo()` from the `Renderable` interface

- CHANGELOG.md
- src/Property/Selector.php
This is the V8.x backport of #1037.
> [TASK] Mark `Selector::isValid()` as `@internal`

- config/phpstan-baseline.neon
- tests/ParserTest.php
- tests/Unit/Property/SelectorTest.php
Mostly move tests from `ParserTest` that belong into
the unit tests.
Part of #757
Part of #758
> [TASK] Add tests for the selector specificity

- CHANGELOG.md
- src/Property/Selector.php
- tests/Functional/Property/SelectorTest.php
- tests/Unit/Property/SelectorTest.php
This is required to be able to drop `__toString` for this class.
> [TASK] Make `Selector` a `Renderable`

- CHANGELOG.md
- src/Property/Selector.php
The return type of `::isValid()` cannot use a native return type declaration yet as the method's return values currently are of a different type (#1043).
Part of #811
> [TASK] Add more native type declarations for `Selector`

- src/CSSList/Document.php
> [CLEANUP] Avoid Hungarian notation for `document`

- src/CSSList/CSSBlockList.php
Also remove the now-unused method `allRuleSets()`.
Part of #994.
> [CLEANUP] Refactor `CSSBlockList::getAllRuleSets()`

- src/RuleSet/RuleSet.php
> [CLEANUP] Improve some variable names in `RuleSet`

- tests/ParserTest.php
> [TASK] Avoid the deprecated `__toString()` in `ParserTest`

- CHANGELOG.md
- src/OutputFormat.php
Instead, the corresponding method on the formatter should be called directly.
This increases type safety and helps static code analysis. Also, it makes the code easier to understand.
> [TASK] Deprecate method forwarding `OutputFormat` to `OutputFormatter`

- src/RuleSet/RuleSet.php
This is the V8.x backport of #1051.
> [BUGFIX] Fix a type annotation in `RuleSet`

- src/Value/Value.php
> [CLEANUP] Avoid Hungarian notation for `*stack*`

- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
This is a pre-patch for #1062.
> Allow rules to be in any order in shorthand tests

- src/Value/Value.php
> [CLEANUP] Avoid Hungarian notation for `*delimiter*`

- src/Value/CalcFunction.php
- src/Value/Value.php
> [CLEANUP] Avoid Hungarian notation for `function`

- src/Value/Value.php
> [CLEANUP] Avoid Hungarian notation in `Value`

- CHANGELOG.md
- src/OutputFormat.php
- src/OutputFormatter.php
This class should only be used for formatting CSS from within this library. It is not intended to be called from outside.
> [TASK] Mark `OutputFormatter` as `@internal`

- src/Value/CalcFunction.php
> [CLEANUP] Avoid Hungarian notation for `calcRuleValueList`

- src/Value/CSSFunction.php
- src/Value/CalcRuleValueList.php
- src/Value/Color.php
- src/Value/LineName.php
- src/Value/ValueList.php
> [CLEANUP] Avoid Hungarian notation for `components`

- src/Value/CalcFunction.php
> [CLEANUP] Avoid Hungarian notation for `lastComponentType`

- src/OutputFormat.php
- src/Parsing/ParserState.php
- src/Rule/Rule.php
- src/Value/CalcFunction.php
> [CLEANUP] Avoid Hungarian notation for `value`

- src/Value/CSSString.php
> [CLEANUP] Avoid Hungarian notation for `begin`

- src/Value/CSSString.php
> [CLEANUP] Avoid Hungarian notation for `quote` (#1080)

- tests/Functional/Value/ValueTest.php
In the tests, we should test parsing and rendering separately as this makes debugging test failures a lot easier.
Part of #1057
> [TASK] Extract value parsing functional tests (part 1)

- CHANGELOG.md
- src/Value/CalcFunction.php
- src/Value/Value.php
- tests/ParserTest.php
- tests/fixtures/calc.css
In the past, vendor prefixes like `-moz-` or `-webkit-` were used for experimental CSS features in browsers. Nowadays, the browsers use features for this instead. Hence, special support for vendor prefixes is no longer needed.
https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix
> [TASK] Drop special support for vendor prefixes

- src/Value/Size.php
> [CLEANUP] Avoid Hungarian notation for `size`

- src/Value/Size.php
> [CLEANUP] Avoid Hungarian notation for `unit` and `sizeUnits`

- src/Value/Size.php
> [CLEANUP] Avoid Hungarian notation for `isColorComponent`

- src/Value/Size.php
> [CLEANUP] Avoid Hungarian notation in `Size::render()`

- src/Value/URL.php
> [CLEANUP] Avoid Hungarian notation for `url`

- src/Value/Size.php
> [CLEANUP] Avoid Hungarian notation for `tokenLength`

- src/Value/Size.php
> [CLEANUP] Avoid Hungarian notation for `sizeUnit`

- src/Value/URL.php
> [CLEANUP] Avoid Hungarian notation for `useUrl`

- src/OutputFormatter.php
> [CLEANUP] Avoid Hungarian notation in `OutputFormatter`

- src/OutputFormat.php
> [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 1)

- src/OutputFormat.php
- src/OutputFormatter.php
- src/Value/Color.php
- tests/Unit/OutputFormatTest.php
As suggested in #1098.
The setters are not changed a those are part of the public API.
> [CLEANUP] Improve some `OutputFormat` property and getter names

- tests/Comment/CommentTest.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
> [CLEANUP] Avoid Hungarian notation in the tests

- src/Property/Selector/SpecificityCalculator.php
> [CLEANUP] Avoid Hungarian notation in `SpecificityCalculator`

- src/CSSList/CSSBlockList.php
> [CLEANUP] Avoid Hungarian notation in `CSSBlockList`

- src/RuleSet/DeclarationBlock.php
> [CLEANUP] Avoid Hungarian notation in `DeclarationBlock`

- config/phpstan-baseline.neon
- tests/OutputFormatTest.php
The `set()` method will be removed soon.
Also unify the tests a bit.
Part of #1103
> [CLEANUP] Use the explicit `OutputFormat` setters in the tests

- CHANGELOG.md
- src/OutputFormat.php
> [TASK] Deprecate `OutputFormat::get()` and `::set()`

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/OutputFormat.php
We now have beautiful, cleanly-typed getters to use instead.
Part of #1103
> [TASK] Remove `OutputFormat::get()`

- src/RuleSet/RuleSet.php
> [CLEANUP] Avoid Hungarian notation in comments

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/OutputFormat.php
> [TASK ] Remove `OutputFormat::set()`

- src/OutputFormat.php
> [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 2)

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `numberOfLines`

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `matches`

- src/OutputFormat.php
> [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 3)

- src/CSSList/AtRuleBlockList.php
- src/OutputFormat.php
- tests/Unit/OutputFormatTest.php
Also rename the (internal) getters to match the changed property names.
Part of #756
> [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 4)

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `input`

- src/OutputFormat.php
> [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 5)

- src/OutputFormat.php
> [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 6)

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `expression`

- src/OutputFormat.php
- src/RuleSet/DeclarationBlock.php
- tests/Unit/OutputFormatTest.php
Also rename the getters to match the new property names.
Part of #756
> [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 7)

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `maximumLength`

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `comment`

- src/Parsing/ParserState.php
> [CLEANUP] Avoid Hungarian notation for `stopCharacters`

- src/OutputFormat.php
- src/OutputFormatter.php
- tests/Unit/OutputFormatTest.php
Also rename the getters to match the new property names.
Part of #756
> [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 8)

- src/OutputFormat.php
- src/OutputFormatter.php
- tests/Unit/OutputFormatTest.php
Also rename the getters to match the new property names.
Part of #756
> [CLEANUP] Avoid Hungarian notation in `OutputFormat` (part 9)

- config/phpstan-baseline.neon
- src/Parsing/ParserState.php
Also make the parameter names non-Hungarian.
Part of #756
> [CLEANUP] Fix some type annotations in `ParserState`

- CHANGELOG.md
- src/OutputFormat.php
This is the V8.x backport of #1131.
> [TASK] Mark the `OutputFormat` as not extendable

- CHANGELOG.md
- src/OutputFormat.php
Also mark the constructor as `@internal`.
> [TASK] Mark `OutputFormat` as not extendable

- tests/Functional/CSSList/DocumentTest.php
> [TASK] Add some rendering tests for `Document`

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/Parsing/ParserState.php
> [TASK] Use native type declarations in `ParserState`

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/CSSList/KeyFrame.php
- tests/Unit/CSSList/KeyFrameTest.php
They fortunately have obvious default values.
This change means it can be enforced that they are always non-empty strings. Type declarations have been updated to reflect that.
> [TASK] Initialize `KeyFrame` properties

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/Property/AtRule.php
The classes implementing this interface use a wide variaty of inconsistent return types when they implement this method.
This is a hard blocker for introducing native return type declaration for this method.
> [TASK] Drop `atRuleArgs()` from the `AtRule` interface

- config/phpstan-baseline.neon
- src/Value/Color.php
> [CLEANUP] Avoid magic method forwarding in `Color`

- config/phpstan-baseline.neon
- src/CSSList/Document.php
> [CLEANUP] Avoid magic method forwarding in `Document`

- config/phpstan-baseline.neon
- src/RuleSet/RuleSet.php
> [CLEANUP] Avoid magic method forwarding in `RuleSet`

- config/phpstan-baseline.neon
- src/Property/Charset.php
> [CLEANUP] Avoid magic method forwarding in `Charset`

- CHANGELOG.md
- src/Value/Size.php
> [TASK] Add native type declarations in `Size`

- tests/Unit/Value/SizeTest.php
> [TASK] Add more unit tests for `Size`

- CHANGELOG.md
- src/Rule/Rule.php
- src/RuleSet/RuleSet.php
- tests/ParserTest.php
- `Rule::parse()` will no longer consume anything after the semicolon terminating the rule - it does not belong to that rule;
- The whitespace and comments before a rule will be processed by `RuleSet::parseRuleSet()` and passed as a parameter to `Rule::parse()` -
- This is only required while 'strict mode' parsing is an option, to avoid having an exception thrown during normal operation (i.e. when `Rule::parse()` encounters normal `}` as opposed to some other junk, which is not distinguished).
Fixes #173.
See also #672, #741.
> [BUGFIX] Include comments for all rules in declaration block

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/Property/Import.php
> [TASK] Add native type declarations for `Import`

- CHANGELOG.md
- src/Property/Selector.php
- tests/Unit/Property/SelectorTest.php
> [BUGFIX] Fix the return type of `Selector::isValid()`

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/Property/Charset.php
> [TASK] Add native type declarations for `Charset`

- tests/Unit/Value/ColorTest.php
- tests/Unit/Value/ValueTest.php
Moving some tests to functional tests and splitting them up will come in later changes for #1057.
> [TASK] Avoid the deprecated `__toString()` in tests

- CHANGELOG.md
- src/CSSList/CSSList.php
> [TASK] Add native type declarations for `CSSList`

- CHANGELOG.md
- config/phpstan-baseline.neon
- src/RuleSet/DeclarationBlock.php
Also add a native type declaration.
This will need more cleanup and refactoring later on.
> [CLEANUP] Fix type annotation of `::getSelectors()`

- tests/CSSList/AtRuleBlockListTest.php
- tests/Comment/CommentTest.php
- tests/OutputFormatTest.php
- tests/ParserTest.php
- tests/RuleSet/DeclarationBlockTest.php
- tests/RuleSet/LenientParsingTest.php
The legacy tests are not very focused. Until we have split them up, try to avoid false positives for code coverage.
Also add `@covers` annotations for the parent classes of the tested classes.
> [TASK] Reduce and finetune the scope of `@covers` annotations

- src/Value/CSSFunction.php
- src/Value/Color.php
- src/Value/RuleValueList.php
- src/Value/Value.php
- src/Value/ValueList.php
Also improve the related type annotations and declarations in other classes in order to keep things consistent and to keep Rector from changing things.
> [TASK] Add native type declarations for `CSSFunction`

- config/phpstan-baseline.neon
- src/Value/Color.php
Also make some types more specific. Also improve code formatting a bit.
Part of #811
> [TASK] Add native type declarations for `Color`

- config/phpstan-baseline.neon
- src/CSSList/CSSList.php
- src/RuleSet/DeclarationBlock.php
- tests/Functional/RuleSet/DeclarationBlockTest.php
Also add clarification of meaning of return value from `CSSList::parseListItem()`, where `null` and `false` have different meanings.
Part of #1176.
> [CLEANUP] Return `null` from `DeclarationBlock::parse()` on failure

- config/phpstan.neon
This will help avoid it suggesting things that are only possile in later PHP versions.
Fixes #1214
> [TASK] Configure the target PHP version for PHPStan

- composer.json
- src/Comment/CommentContainer.php
- src/Comment/Commentable.php
- tests/Unit/Comment/CommentContainerTest.php
- tests/Unit/Comment/Fixtures/ConcreteCommentContainer.php
> [TASK] Add trait providing standard implementation of `Commentable`

- src/CSSList/CSSList.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Rule/Rule.php
- src/RuleSet/RuleSet.php
> [TASK] Use `CommentContainer` trait to implement `Commentable`

- .github/dependabot.yml
Version 3.0 of this package is not compatible.
> [TASK] Prevent Dependabot updating "rawr/cross-data-providers"

- CHANGELOG.md
Also remove superfluous 'the' in another entry.
> [CLEANUP] Move magic deprecation changelog entry to correct section

- CHANGELOG.md
(And one that was missed from 8.7.)
> [TASK] Integrate changelog entries from 8.8 release

- README.md
> [TASK] Add to UML diagram that `Selector` implements `Renderable`

- README.md
> [TASK] Update class diagram to include `CSSListItem`

- .github/dependabot.yml
- composer.json
- tests/Unit/Comment/CommentContainerTest.php
- tests/Unit/Position/PositionTest.php
The package `rawr/cross-data-providers` that we used has been abandoned and should not be used anymore.
> [TASK] Migrate to `rawr/phpunit-data-provider`

- CHANGELOG.md
- README.md
- src/CSSList/CSSList.php
- src/Comment/Comment.php
- src/Parsing/SourceException.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSFunction.php
- src/Value/Value.php
> [TASK] Implement `Positionable`

- src/Position/Positionable.php
The deprecation and changes from #1207 can be merged to 8.x. See #1232.
So the deprecation can be brought forward.
> [TASK] Deprecate `getLineNo()` etc. in v8.9.0

- CHANGELOG.md
- composer.json
- src/CSSList/CSSList.php
- src/Comment/Comment.php
- src/Parsing/SourceException.php
- src/Position/Position.php
- src/Position/Positionable.php
- src/Property/CSSNamespace.php
- src/Property/Charset.php
- src/Property/Import.php
- src/Rule/Rule.php
- src/RuleSet/DeclarationBlock.php
- src/RuleSet/RuleSet.php
- src/Value/CSSFunction.php
- src/Value/Value.php
- tests/Unit/Position/Fixtures/ConcretePosition.php
- tests/Unit/Position/PositionTest.php
- tests/UnitDeprecated/Position/PositionTest.php
This is the backport of #1221 and #1225 for #1207.
> [TASK] Add and implement `Positionable` interface

- tests/Unit/CSSList/AtRuleBlockListTest.php
Use the interface type to be tested for in the assertion, not the type of the object itself.
> [BUGFIX] Correct `AtRuleBlockListTest::implementsAtRule()`

- CHANGELOG.md
- README.md
- src/CSSElement.php
- src/CSSList/CSSBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/Rule/Rule.php
- src/RuleSet/RuleSet.php
- src/Value/Value.php
- tests/Unit/CSSList/CSSListTest.php
- tests/Unit/Rule/RuleTest.php
- tests/Unit/RuleSet/Fixtures/ConcreteRuleSet.php
- tests/Unit/RuleSet/RuleSetTest.php
- tests/Unit/Value/Fixtures/ConcreteValue.php
- tests/Unit/Value/ValueTest.php
Also add tests to confirm that the supplanted types in the DocBlock actually implement the new interface.
And correct a DocBlock type to also allow `string`, which is currently possible.
cf. #1230
> [TASK] Add and implement `CSSElement` interface

- tests/Unit/CSSList/AtRuleBlockListTest.php
- tests/Unit/CSSList/CSSListTest.php
- tests/Unit/CSSList/KeyFrameTest.php
- tests/Unit/Property/CSSNamespaceTest.php
- tests/Unit/Property/CharsetTest.php
- tests/Unit/Property/ImportTest.php
- tests/Unit/RuleSet/AtRuleSetTest.php
- tests/Unit/RuleSet/DeclarationBlockTest.php
- tests/Unit/RuleSet/RuleSetTest.php
These should probably have been added as part of #1212. They confirm that the various types supplanted by `CSSListItem` in the API all implement the new interface.
Resolves #1236.
> [TASK] Add `assertInstanceOf` tests for `CSSListItem`

- src/CSSList/CSSBlockList.php
Change the one remaining usage instance to use `getAllDeclarationBlocks()`, which was refactored in #990.
Part of #994.
> [CLEANUP] Remove `CSSBlockList::allDeclarationBlocks()`

- src/CSSList/CSSBlockList.php
- src/CSSList/Document.php
- tests/Unit/CSSList/CSSBlockListTest.php
Also add unit tests for this method.
Part of #994.  Relates to #1230.
> [TASK] Move `getAllValues()` to `CSSBlockList`

- CHANGELOG.md
- src/CSSList/CSSBlockList.php
- tests/Unit/CSSList/CSSBlockListTest.php
The `$element` parameter was overloaded with a dual purpose.
A second separate parameter has been added for rule filtering, which is not actually mutually exclusive with CSS subtree selection.
Since `getAllValues()` is part of the public API, the method now supports being called with the old or new signatures, with the old signature being deprecated.
Once the deprecation has been included in the 8.x release branch, the messiness of supporting the previous API can be removed.
Part of #994.  Also relates to #1230.
> [TASK] Deconflate `getAllValues()` parameters

- CHANGELOG.md
- src/CSSElement.php
- src/CSSList/CSSBlockList.php
- src/CSSList/CSSList.php
- src/CSSList/Document.php
- src/Rule/Rule.php
- src/RuleSet/RuleSet.php
- src/Value/Value.php
- tests/Unit/CSSList/CSSBlockListTest.php
- tests/Unit/CSSList/CSSListTest.php
- tests/Unit/CSSList/Fixtures/ConcreteCSSBlockList.php
- tests/Unit/CSSList/Fixtures/ConcreteCSSList.php
- tests/Unit/Rule/RuleTest.php
- tests/Unit/RuleSet/Fixtures/ConcreteRuleSet.php
- tests/Unit/RuleSet/RuleSetTest.php
- tests/Unit/Value/Fixtures/ConcreteValue.php
- tests/Unit/Value/ValueTest.php
This is the backport of #1231, #1240 and #1241.
cf. #1230
> [TASK] Deconflate getAllValues() parameters

- CHANGELOG.md
- src/CSSList/CSSBlockList.php
- tests/ParserTest.php
- tests/Unit/CSSList/CSSBlockListTest.php
The method still exists with the same (slightly improved) functionality, but the optional arguments have been refactored, and may require changes.
Part of #994.  Closes #1230.
> [TASK] Remove original `getAllValues()` API

- src/CSSList/CSSBlockList.php
Move functionality from `allValues()` directly into to `getAllValues()`, so as to avoid passing array by reference, removing `allValues()`. Avoid making the recursive call for nested items that are not `CSSElement`s.
Part of #994.
Closes #1230.
> [TASK] Refactor `getAllValues()`

- src/CSSList/CSSBlockList.php
- src/CSSList/Document.php
The renamed (internal) method now returns the result, instead of having a reference parameter for it.
Closes #994.
> [CLEANUP] `allSelectors()` -> `getAllSelectors()`

- config/phpstan-baseline.neon
- src/RuleSet/RuleSet.php
Use `=== null` instead to be more precise.
> [CLEANUP] Avoid negated non-Boolean in `RuleSet`

- CHANGELOG.md
- src/RuleSet/RuleSet.php
And also `getRulesAssoc()`.
Relates to #1247.
> [TASK] Deprecate passing `Rule` to `RuleSet::getRules()`

- CHANGELOG.md
- src/RuleSet/RuleSet.php
- tests/Unit/RuleSet/RuleSetTest.php
Passing `string` or `null` to `removeRule()` is deprecated. The new methods handle that functionality.
Relates to #1247.
> [TASK] Add separate methods for `RuleSet::removeRule()`, with deprecation

- config/phpstan-baseline.neon
- tests/ParserTest.php
Now this method has been added, using it appropriately in the tests, rather than the deprecated functionality, will eliminate a PHPStan warning.
Note that PHPStan seems to erroneously place the warning against the callee rather than the caller.
> [CLEANUP] Use `RuleSet::removeMatchingRules()` in tests

- CHANGELOG.md
- src/RuleSet/RuleSet.php
> [TASK] Allow only `Rule` to be passed to `RuleSet::removeRule()`

- tests/ParserTest.php
Now the interface has been added, it is no longer necessary to check the object is one of a long list of types.
Also use the new `getLineNumber()` instead of the deprecated `getLineNo()`.
> [CLEANUP] Check for `Positionable` in `lineNumbersParsing()` test

- CHANGELOG.md
- README.md
- src/CSSList/CSSBlockList.php
- src/RuleSet/RuleContainer.php
- src/RuleSet/RuleSet.php
- tests/Unit/RuleSet/RuleSetTest.php
This covers the maniplation of `Rule`s within the container, and may be implemented by other classes in future (e.g. #1194).
Note that the naming is consistent with the current codebase, rather than what the CSS entities are now called:
- `Rule` represents what is now called a "declaration";
- `RuleSet` represents what is now called a "declaration block";
- `DeclarationBlock` represents what is now called a "style rule";
- `CSSListItem` (closely) represents what is now generically called a "rule".
Renaming things is part of a longer-term plan touched on in #1189.
> [TASK] Add interface `RuleContainer` for `RuleSet`

- CHANGELOG.md
- src/Position/Position.php
- src/Position/Positionable.php
This will aid writing tests for `RuleSet`.
Note that the PHP type annotation cannot be `self` because an interface is involved and PHP 7 is still supported.
Part of #974.
> [TASK] Have `setPosition()` implement fluent interface

- tests/Unit/RuleSet/RuleSetTest.php
The same objects may be provided to multiple tests. If a test manipulates an object,
it will no longer be in the initial expected state for other tests.
> [BUGFIX] Don't return objects from data providers

- CHANGELOG.md
- src/RuleSet/RuleSet.php
- tests/Unit/RuleSet/RuleSetTest.php
Continue to preserve the column number.
Also tighten the test to confirm the `Rule` is added at the end.
Note that the reason for `markTestSkipped()` was incorrect - the line number was not being set at all.
> [BUGFIX] Set line number for `addRule()` with only column number

- tests/Unit/RuleSet/RuleSetTest.php
Some tests are skipped pending bug fixes.
Part of #974.
> [TASK] Add tests for `addRule()` with a sibling

- src/RuleSet/RuleSet.php
As well as being used with `usort()`, it may have other uses.
The deprecated `getLineNo()` and `getColNo()` are still used for now. Replacing these will be done separately.
Relates to #974.
> [CLEANUP] Extract method `RuleSet::comparePositionable`

- tests/Unit/RuleSet/RuleSetTest.php
These were previously testing more than one aspect of a `RuleSet` method. Now each behaviour has a dedicated test method (albeit with some duplication of the set-up).
Also added an additional assertion when there are no expected remaining items following removal, so that an assertion is made.
> [CLEANUP] Separate some test methods in `RuleSetTest`

- tests/Unit/CSSList/AtRuleBlockListTest.php
- tests/Unit/CSSList/CSSListTest.php
- tests/Unit/CSSList/KeyFrameTest.php
- tests/Unit/Comment/CommentTest.php
- tests/Unit/Parsing/OutputExceptionTest.php
- tests/Unit/Parsing/SourceExceptionTest.php
- tests/Unit/Parsing/UnexpectedEOFExceptionTest.php
- tests/Unit/Parsing/UnexpectedTokenExceptionTest.php
- tests/Unit/Value/CSSStringTest.php
- tests/Unit/Value/CalcRuleValueListTest.php
- tests/Unit/Value/URLTest.php
These correspond to the existing tests for `getLineNo` for classes that implement `Positionable`.
Also correct an existing test method name to refer to `getLineNo`.
> [TASK] Add tests for `getLineNumber`

- CHANGELOG.md
- src/Position/Position.php
- src/Position/Positionable.php
- tests/UnitDeprecated/Position/PositionTest.php
Note that the removed tests are in `UnitDeprecated`. Equivalent tests already exist for the replacement `getColumnNumber()`.
Part of #974
> [TASK] Remove `getColNo()`

- src/Parsing/SourceException.php
- tests/Unit/Parsing/SourceExceptionTest.php
The bug was introduced by #1288, so has not been included in any release; thus a changelog entry is not justified.
> [BUGFIX] Exclude absent line number from exception message

- CHANGELOG.md
- src/Property/Selector.php
- tests/Unit/Property/SelectorTest.php
Also add a note that the specificity is incorrectly calculated in such cases. This will be addressed with a separate fix.
> [BUGFIX] Allow comma in selectors

- README.md
- adapt the sorting to how the diagram generator sorts
- add `SpecificityCalculator` which had been missing
> [DOCS] Fix class list in class diagram

- README.md
This is in preparation for adding a script for generating the class diagram in #1297.
> [DOCS] Make the class diagram markers generator-friendly

- README.md
As long as we manually edit the source of the class diagram, having markers for a part being autogenerated does not make sense.
> [DOCS] Temporarily drop some markers from the class diagram

- CHANGELOG.md
This way, the upcoming 9.0.0 release won't have changes in the changelog that already are part of the 8.9.0 changelog.
> [DOCS] Integrate the 8.9.0 changelog into main changelog

- config/rector.php
Since #1201, this becomes a duplicate.
> [CLEANUP] Remove superfluous Rector rule

- config/phpstan-baseline.neon
- src/CSSList/CSSList.php
The parameter `$parserState` is specified to be a `ParserState`, so it can never be a string.
> [CLEANUP] Remove impossible conditional

- src/RuleSet/RuleSet.php
... to be consistent with the class now being concrete.
Missed in #1341.
> [CLEANUP] Update `RuleSet` DocBlock

- .github/dependabot.yml
- composer.json
- config/php-cs-fixer.php
Safe-PHP https://github.com/thecodingmachine/safe provides rewrites of PHP functions to throw an exception instead of returning `false` when an error is encountered.
This will allow us to drop out custom `preg_*` wrapper class and to increase type safety in our codebase.
Also drop the PHP-CS-Fixer rule that adds a trailing backslash to calls to native PHP functions (as this would change the Safe-PHP calls back to their unsafe versions).
The actual code changes will come in subsequent commits.
Part of #1168
> [TASK] Add `thecodingmachine/safe` (#1453)

- CHANGELOG.md
- src/Property/KeyframeSelector.php
- src/Property/Selector.php
Avoid [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html) in selector validation regular expression by using possessive quantifier with mutually exclusive alternations.
Also remove outdated description from DocBlock, but add description for extended class summarizing differences.
> [BUGFIX] Improve selector validation performance

- CHANGELOG.md
- src/Value/CSSString.php
> [BUGFIX] Use safe preg functions in `CSSString`

- CHANGELOG.md
- src/Rule/Rule.php
> [BUGFIX] Use safe preg functions in `Rule`

- CHANGELOG.md
- src/Property/Selector/SpecificityCalculator.php
> [BUGFIX] Use safe preg functions in `SpecificityCalculator`
